### ISSUE TITLE
Failed to load the classes for a few blocks

### ISSUE THREAD

**Issue by misterfixit** [bdew-minecraft/generators#1]
http://puu.sh/b2m7j/8b695fd591.txt

**Comment by bdew** [comment]
I have no idea what's going on here, possibly a corrupted install or coremod shenanigans. Try re-downloading and if that fails please post a full log.

**Comment by bdew** [comment]
Can you try re-downloading from here: https://www.dropbox.com/sh/ihdi0o5j0wcx9fd/AAD2xetlcW0qrHGrmsdDAU-xa

**Comment by misterfixit** [comment]
I was using BDLIB 1.4.2.9 I was using the download link off of your pressure pipes link on http://bdew.net/pressure/ the bdlib 1.4.3.13 loads up haven't played with it in world

**Comment by bdew** [comment]
Was this fixed?

**Comment by misterfixit** [comment]
yes this was fixed
