### ISSUE TITLE
[Request] Register Syngas as a fuel.

### ISSUE THREAD

**Issue by cloakable** [bdew-minecraft/generators#100]
Could you register Syngas as a BC fuel so it can be burned in generators compatible with that, other than Advanced Generators?

**Comment by Dragnier** [comment]
I second that, Ender IO recognizes BC registered fuels as well. I actually posted an issue over there about how to get EIO to recognize a syngas a fuel and they responded with stuff that, as far as I know, can only be done by a mod author. Here is a link: https://github.com/SleepyTrousers/EnderIO/issues/3430#issuecomment-227276122

**Comment by bdew** [comment]
I'm currently focusing my development on 1.9.4 and there is no BC for that version yet.

I'll add it when they update, and possibly for older versions (1.7.10/1.8.9) if i end up doing another update for them (but currently i'm not planning one).

**Comment by Dragnier** [comment]
My understanding is that you can still use BC to add them in 1.9.4+ even though the BC mod itself isn't updated, but I could be wrong. Take a look at what they said on my link there.

**Comment by DaemosDaen** [comment]
Fuel is not registered as a fuel via BC, it's registered thought Forge. The code was donated/lifted by/from BC WAAAAAAAAAYYYY back in the day and I believe the code was largely left unchanged, thus all the references to BC when talking about it.

**Comment by bdew** [comment]
We are talking about liquid fuels, what forge handles are solids (for e.g. furnaces).

(And yes, i'll add this soon(tm))

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
