### ISSUE TITLE
[0.9.20.5] Heat Exchanger Fluids are broken

### ISSUE THREAD

**Issue by qinsignificance** [bdew-minecraft/generators#104]
Lava is able to enter the water and lava slot, and water is able to enter the lava and water slot. Basically there is no restrictions with the built in tanks. Pretty sure it broke with the new api change for liquids

**Comment by bdew** [comment]
Check with Advanced Generators 0.9.20.6 and BDLib 1.12.1.4, i'm pretty sure this is already fixed.
