### ISSUE TITLE
1.10.2 Server crash loop

### ISSUE THREAD

**Issue by Xobias** [bdew-minecraft/generators#108]
Unsure whether this is an issue with Advanced Generators or Ender IO however the attached crash log has been generated by one of the members on my server. He was connecting an Ender IO fluid conduit (top tier ender I think) to a fluid input port but when configuring it to in port they turned off needing a redstone signal to work while it was configured to export. So the pipe is trying to output from an input.

Mod Version: generators-0.9.20.9-mc1.10.2.jar

[crash-2016-07-25_21.57.46-server.txt](https://github.com/bdew/generators/files/382590/crash-2016-07-25_21.57.46-server.txt)

**Comment by bdew** [comment]
I think it's a bug in bdlib. Try updating to this build - http://minecraft.curseforge.com/projects/bdlib/files/2318792 and see if it fixes it.

**Comment by Xobias** [comment]
Seems to be ok will let you know if we have other issues. Thanks.
