### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rannday** [bdew-minecraft/generators#113]
[http://pastebin.com/LqhM4gfT](url)

Was playing around with heat exchangers and steam generators. Can no longer access the world.

Placed a fluid intake valve connected to a steam generator next an Extra Utilities 2 transfer pipe  pumping water into the heat exchanger.

**Comment by bdew** [comment]
Try this build of bdlib: https://minecraft.curseforge.com/projects/bdlib/files/2326126

I think it should fix the crash.
