### ISSUE TITLE
Cannot get gas turbine generator to output into Mekanism universal basic cable (MC1.10.2) 

### ISSUE THREAD

**Issue by ab9rf** [bdew-minecraft/generators#114]
Cable binds to the flux generator module, but generator does not output RF. Generator generates power, but it never goes anywhere.

Using generators-0.9.20.10, bdlib-1.12.2.8-mc1.10.2, Mekanism-1.10.2-9.1.1.29

Update: the generator will push power into a Mekanism energy cube, just not into a Mekanism universal cable.

Cross-ref: aidancbrady/Mekanism#3693

**Comment by bdew** [comment]
This is not really fixable on my side. I posted more details in the other issue.
