### ISSUE TITLE
Add higher tier fuels from Actually Additions

### ISSUE THREAD

**Issue by demethan** [bdew-minecraft/generators#117]
Hi, 

We are trying to put together an updated version of Breafast Special for breakfastcraft.com

Would it be possible to add support on 1.10.2 for Actually Additions oil. 

Many Thanks.  Love the mod, its in all our packs. :)

https://github.com/Ellpeck/ActuallyAdditions/issues/259#event-801537303

**Comment by Winrylive** [comment]
Hi Dem!

Actually Additions oil is compatible (https://github.com/bdew/generators/issues/115), but tier 2 (Crystalized) and tier 3 (Empowered) oils added in the most recent version of AA are not.  I'm using AA Oil on Spilled Juice, another Breakfastcraft pack BDew.

Adding tier 2 and 3 oils would be great! Here's their numbers in case you need them.

![2016-09-25_14 55 45](https://cloud.githubusercontent.com/assets/17501344/18817816/35ce298c-8330-11e6-86d4-4a5cf2f1638a.png)

**Comment by demethan** [comment]
*facepalm..  my bad.. 

Another case of right hand not talking to left hand.

**Comment by bdew** [comment]
Retitling and reopening so i don't forget :P

**Comment by Tsukiumy** [comment]
just to update, the new values for the oils are as follow
oil:100 RF/t | 200 RF/mB
cristalized oil: 200 RF/t | 400 RF/mB
empowered oil: 350 RF/t | 700 RF/mB

**Comment by bdew** [comment]
Sorry for the long delay. I've tested it myself and the numbers i got matched what @Tsukiumy posted so i'll use those.

Will add to default configs in next build.
