### ISSUE TITLE
Voltage Emitters Only Emit EU When Connected To A Cable

### ISSUE THREAD

**Issue by makromoo** [bdew-minecraft/generators#118]
According to WAILA and the Turbine Controller the energy stored is in RF. No EU is emitted nor any other power type for that matter.

**Comment by bdew** [comment]
WAILA and the GUI show the internal storage in whatever unit that's configured in the client config.

What are you connecting to the emitter? And what version?

**Comment by makromoo** [comment]
Tried connecting it to a MFSU and mass fab and no power output.
I notice the setup I had built in my test world a while back was working fine. However, when I constructed a new setup then it did not emit EU. It is only the emitter (EU) that isn't functioning.

Running IC2 experimental 2.2.6.84-ex110
bdlib 1.12.2.12
Advanced Generators  0.9.20.14

**Comment by makromoo** [comment]
Strangely enough, the version of Advanced Generators I was running when the generator was emitting EU in the test world is the same version of the mod as I am using now...

**Comment by makromoo** [comment]
http://imgur.com/a/qKrtU
Picture of set-up of generators. Notice the working generators has red arrows whereas the non-working generator does not. Very strange indeed.

**Comment by makromoo** [comment]
Scratch most of the above out. EU is only emitted when it is connected to a cable. So when it is directly hooked up to a transformer or storage unit then it does not work.

**Comment by bdew** [comment]
Hm, interesting, i'll take a look into it. IC2 e-net is sometimes very weird :P

**Comment by bdew** [comment]
Should be fixed in next build
