### ISSUE TITLE
Crystallized and Empowered Oil

### ISSUE THREAD

**Issue by Fortanono** [bdew-minecraft/generators#121]
Actually Additions Oil seems to be a fuel, but the Crystallized and Empowered versions are not. Could you add them? 

EDIT: Okay, this is strange. Found the commit where you added this, but in All the Mods Lite it isn't showing up. AG is in the latest version that is available on Curse and there doesn't seem to be anything in the config disabling it. So... did you remove the change?

**Comment by Fortanono** [comment]
Okay, this is strange. Found the commit where you added this, but in All the Mods Lite it isn't showing up. AG is in the latest version that is available on Curse and there doesn't seem to be anything in the config disabling it. So... did you remove the change?

**Comment by bdew** [comment]
Do they have 0.9.20.19? I added that change only in the last build.

**Comment by Fortanono** [comment]
No, actually. That'll do it.

At the same time, though, I unlocked the profile and Curse doesn't say that the mod needs an update.
