### ISSUE TITLE
A question on renaming a jar file

### ISSUE THREAD

**Issue by xenoflot** [bdew-minecraft/generators#122]
Hi, 

This isn't an issue (unless you feel it's one) but a question to help me understand. I renamed the generators jar file to advgenerators on my server to aid in sorting against my modlist and I found that when I tried to connect with the client with the default name, that the server rejected me for Missing list: _[advgenerators:steam, advgenerators:steam]_

Can you tell me why renaming the file caused this problem? I would've thought that the forge MOD_ID as specified in the source should've been the only handle used once things are running.

Thanks!

**Comment by bdew** [comment]
No idea TBH, the name of the jar shouldn't affect anything i think... maybe a bug in FML?

**Comment by xenoflot** [comment]
OK then. Thanks for the quick reply. I'll try it with another couple of mods in the morning and if happens with other mods, I'll close this and report it over there. I'll be back!

**Comment by bdew** [comment]
Actually i think i know what it might be. The filename could affect the loading order of mods (specifically mods that don't have any kind of dependency on each other.).

Advanced generators only registers the steam fluid/block if no other mod provides it. It might be that on the client it loads after something else that registers steam so the version in AG isn't registered. While on the server it loads before that other mod so it's registered on the server... and you end up with missing blocks when connecting.

**Comment by xenoflot** [comment]
Ah hah! Yes, I have IC2 which definitely registers steam and a few other tech mods in there that may do. That answers that then. Thanks kindly for your brain!

**Comment by xenoflot** [comment]
and all your hard work and generosity in giving us a wonderful mod!
