### ISSUE TITLE
1.11.2 crash

### ISSUE THREAD

**Issue by 5kedone** [bdew-minecraft/generators#126]
latest forge( at time of posting) 

when ever i try to make anything with quartz enriched iron the game crashes and log points to this mod 

Crash does not happen without it 

http://pastebin.com/LaJSVn68

**Comment by bdew** [comment]
The bug is actually in Gendustry not advanced generators.

Should be fixed in this build: https://jenkins.bdew.net/job/gendustry-1.11.2/2/artifact/build/libs/gendustry-1.6.5.2-mc1.11.2.jar

If it isn't, please open a bug report over on Gendustry bug tracker.

**Comment by 5kedone** [comment]
Oh god I didn't post in wrong one lol sorry about that good thing you make
both lol ,what a twat I am , will let you know in 20 mins just eating
dinner
