### ISSUE TITLE
Can't pipe in water into machines. [1.11.2]

### ISSUE THREAD

**Issue by megaloloful** [bdew-minecraft/generators#128]
I've tried different ways (actually additions fluid lasers and XU2 fluid nodes) and none of them work
Piping Syngas into a gas generator works though
bdlib 1.13.1.3mc1.11.2
Advanced generators 0.9.20.2-mc1.11.2
Forge12.20.0.2226

**Comment by bdew** [comment]
Possibly same bug as #123

I've added the fix to 1.11.2 branch, please try BDLib 1.13.1.4 + Advanced Generators 0.9.20.3

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
