### ISSUE TITLE
Missing Textures in JEI for Minecraft 1.11.2

### ISSUE THREAD

**Issue by SpeedSlider** [bdew-minecraft/generators#129]
The following textures show up with the pink and black missing texture icon in JEI and is possibly due to not following the all lowercase file name rule implemented in Minecraft 1.11. Also this appears to cause crashes when using Optifine.

-Control Circuit (also note that control is missing a capitalized C in the JEI when hovering the cursor over it)
-Sensor Module (also missing capitalized S in sensor when hovering the cursor over it)
-Redstone Control Module
![2017-02-01_12 18 43](https://cloud.githubusercontent.com/assets/25437944/22517878/9c70e88e-e878-11e6-9e00-91d893d7cb9b.png)

**Comment by bdew** [comment]
Oops, looks like i missed a few things when renaming stuff. Should be fixed in next build, thanks for the report.
