### ISSUE TITLE
Fuel Types not working

### ISSUE THREAD

**Issue by Harkole** [bdew-minecraft/generators#13]
Latest version of Advanced Generators, BuildCraft and Thermal Expansion (Beta) MineFactory for Minecraft 1.7.10.

Have seen the note on the home page and I'm using the EnderIO version 2.2.0.272, so should be above the version listed as causing a problem? Willing to accept this as the cause though. We do not have Forestry.

The only fuel being accepted by default is BioFuel, although NEI does show information for both RocketFuel and BC's Fuel they won't be accepted by the Generator.

Attempting to pipe all fuels in through waterproof gold pipes from a BC tank to the fluid intake block, set up must be correct as BioFuel is accepted.

I haven't had chance to check if this can be fixed by sepcifing over riding config files yet, will update with if that works later today.

**Comment by bdew** [comment]
You probably have some other mod with BC 6.0 API included that messes this up. Post your forge log if you can't figure out which one.

**Comment by Harkole** [comment]
I should of thought on about that when I saw the other old API issues. I'm currently at work but expect you are correct I'll have a look when I get home and confirm this is the case. Apologies for raising an issue on a known fault.

**Comment by HCSarise** [comment]
I'm having this issue as well, can you explain to me in simple terms what I need to do to fix it?

**Comment by bdew** [comment]
Update your mods that still ship the old BuildCraft API with them. If you can't figure out which ones are those - post your forge log and i'll look into it.

**Comment by Harkole** [comment]
I worked around the problem by creating a custom fuel config file adding in
rocket fuel and build craft fuel although I don't know if they have the
standard fuel values.

If Bdew posts what the intended values are I can post the file and you just
need to put it in the AdvGenerators folder in the config folder.

**Comment by bdew** [comment]
The values should be

```
recipes {
    turbine-fuel: fuel 150 MJ/mB
    turbine-fuel: rocket_fuel 112 MJ/mB
    turbine-fuel: fire_water 120 MJ/mB
}
```

**Comment by Harkole** [comment]
Thanks will post the config file shortly

**Comment by bdew** [comment]
I've edited the message above to be in the right format :P

**Comment by Harkole** [comment]
Saved me writing the config file! :)

Remember HCSarise that the official website holds information on getting the items out of the game to add other fuels to the turbine (/dumpregistry) that you then add to the above something like:

```
recipes {
    turbine-fuel: fuel 150 MJ/mB
    turbine-fuel: rocket_fuel 112 MJ/mB
    turbine-fuel: fire_water 120 MJ/mB

    // IC2 & RailCraft Steam examples - values are guess work!
    turbine-fuel: ic2steam 100MJ/mB
    turbine-fuel: steam 100MJ/mB
}
```

I am curious why you have the values like you do...

BC Fuel gives better energy return than Ender's Rocket Fuel when Rocket Fuel is more costly to make (2 Vats, one making hooch - easy as just plant life, however the second is using gunpowder and redstone) while BC Fuel is relatively cheap requiring only one diamond in construction materials for the refinary then just power to do the oil to fuel conversion.

I'd set my values as 160MJ/mB for fuel but 220MJ/mB for Rocket Fuel as initial settings, am I miss understanding the fuel multipliers or was there another reason for making BC Fuel better?

**Comment by bdew** [comment]
> I'd set my values as 160MJ/mB for fuel but 220MJ/mB for Rocket Fuel as initial settings, am I miss understanding the fuel multipliers or was there another reason for making BC Fuel better?

The values are taken from what EnderIO and Buildcraft itself registers in BC fuel registry, i just provided them for those that can't get it to work due to API conflicts. When everything works correctly you can tweak their value in their respective config files.

Also for steam 100 is waaaay OP. If i remember my math correctly, steam is worth between like 0.2 MJ/mB (in RC) and 1.1 MJ/mB (in high end BR turbines).

**Comment by Harkole** [comment]
Yeah I thought Steam was way too high! Thanks for the information, I didn't know BC had a fuel register. Do you need to pull that from the BC API/Java or can you get at it in game?

Either way I'll mark this as closed, thank you for the help and information.

**Comment by HCSarise** [comment]
I'm still confused about what to do, I did the /dumpregistry command and found where the file was saved but Windows doesn't recognize any program that can open the file.

**Comment by Harkole** [comment]
Right click it and choose open with then notepad. You then need to scroll to the bottom of the list for the fluids section and lift the names of the fluids you want to use in to a new config file.

You can probably just copy and paste BDew's recipies in to a file called myConfig.cfg  and put that in to the AdvGenerators config folder next to the existing ReadMe.txt file.

Restart the server if it is this you are doing or start the client up once the file is in place and it should then work.

**Comment by bdew** [comment]
Either what @Harkole said above, or post your log (logs\fml-client-latest.log) and i'll tell you what mod you need to update.

> Do you need to pull that from the BC API/Java or can you get at it in game?

I think NeiPlugins used to show that when you clicked to fluid in NEI, but i'm not sure if it's still in recent versions.

**Comment by HCSarise** [comment]
The config file thing worked. Was gonna try to use pastebin to get my logs to you as well but it said I exceeded the file size for a guest user. Don't really wanna make an account there - will a simple modlist do?

**Comment by bdew** [comment]
No, i can't really check every mod, the log shows where it loads APIs from.

You can search it for a line that says something like:

> BuildCraftAPI|fuels(API: BuildCraftAPI|fuels:1.0): **<name of the file will be here>** ()

You can also upload it to dropbox or somesuch if that doesn't help.

**Comment by airsoft-slayer** [comment]
sorry to bring this up again, but i dont know anything about coding, please can i have the complete config and instructions on what to do with it and where to put it. Thanks.

**Comment by Harkole** [comment]
At work at the moment let me see if I can find it for you

**Comment by Harkole** [comment]
@airsoft-slayer now I'm at home and able to check over a few things the instructions above are valid, the file lives in your Minecraft/Config folder where ever you've installed it to, simply add the config file and put in the values in the format above. Start the game/server and those values will be present.

Can't really help much more without more details.

**Comment by bdew** [comment]
I've added a crapton of default values for fuels from many mods since this issue was orifinally opened.

What exactly are you missing?

**Comment by airsoft-slayer** [comment]
@bdew ,fuels from buildcraft, ic2 and ender io are not being recognized by the generator, with the fuel slot saying "empty". I am running version 0.9.17.102 of advanced generators.

**Comment by bdew** [comment]
All those should be working, look in yout forge log, it should have a list of all registered fuels (look for "Turbine fuels:")
