### ISSUE TITLE
[BUG] Syngas Producer

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/generators#130]
Not sure if this is a bug but it certainly was painful tonight.

Apparently the syngas generator will take darn near any item you feed it. You get nothing for them if they have no carbon value of course. It ate my Bag of Holding from Eu2 complete with most of my gear. Is that intended functionality or should it only take fuel items with carbon values?

I'm going to go cry now.

**Comment by bdew** [comment]
Hm, no, it should only take items with carbon value.
What version is that on? And any custom configs?

**Comment by Utildayael** [comment]
Hi Bdew,

Sorry I forgot the important bits!

MC 1.10.2
Adv Gen 0.9.20.19

Ya it was a very painful experience. 

Thanks for looking in to this. I figured your intention was to keep it like most machines where it wont accept items it can't use. :)

Thanks!

**Comment by Utildayael** [comment]
Oops. One more bit. No custom config for Adv Gen. Just the stock defaults.

**Comment by Utildayael** [comment]
Double oops. User error. Disregard. :)
