### ISSUE TITLE
Request - More Generators

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/generators#131]
First off, like Pressure Pipes I love this mod. While it can be really expensive to build out the generators given their output compared to other mods, they're pretty balanced and. Let importantly, they are completely modular and upgradable! They grow with you which is awesome as every other mod is rip out and replace. 

That said, had some ideas for a couple new gens to flesh out the tiers a little better I wanted to share. 

1. Solar. Low tier. Works only during the day. Blocks would be controller, panels, misc items related to solar generation since it's really steam power via solar so fluid input, turbines, etc. Panels require sky view of course. 

2. Hydroelectric. Works with water! Needs pressurized water to spin turbines to create power. Low tier like solar with limited output.  Easy to craft as a starter power source much like Immersive Engineering's waterwheels. If you can't do falling water physics like say, RotaryCraft's water mill, suggest a pump system that runs off a power block which is just a basic coal generator so it requires power to make more power and gives it a cost. 

3. Nuclear! High tier. Runs on uranium (IC2/IE) or the Big Reactor (Extreme Reactors in 1.10) fuels (Yellorite, etc). Parts include controller, turbines, steam producers, chambers for the reaction, cooling towers/vents, etc. Add machine to process uranium and make fuel rods. Nuke reactor produces nuclear waste. 

4. Wind. Low tier. Altitude-dependent. Controller. Turbine. Etc. 

Other:

Would be cool to have "structural blocks" which are dummy blocks like steel scaffolding that can be used to link your generator together like a normal generator block. This would just give some different building options as all the proper generator blocks wouldn't have to touch if they had these between them. It would still be the multiblock, just I could run like:

Gas Turbine Controller > steel scaffold > turbine and it would be a legit structure. 

Cheers

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
