### ISSUE TITLE
No recipe for Forge Energy output

### ISSUE THREAD

**Issue by CplPibald** [bdew-minecraft/generators#133]
The Forge Energy output block (in-game "Energy Emitter") doesn't have a recipe.  The block is listed in JEI and available via cheats, but can't be created in normal survival mode.

generators-0.9.20.3-mc1.11.2.jar

Workaround: 
1. Open the jar with 7zip and go to assets/advgenerators/config.
2. Copy recipes.cfg to your config folder in config/AdvGenerators/overrides
3. Add the following lines to your copy of recipes.cfg

    RMR
    FWF => B:advgenerators:forge_output
    RwR

**Comment by bdew** [comment]
Fix merged, thanks!
