### ISSUE TITLE
Flux Generator does not work with Mekanism universal cables

### ISSUE THREAD

**Issue by Givemeyourgits** [bdew-minecraft/generators#136]
When connecting Mekanism universal cable the generator acts as if nothing is connected.

**Comment by bdew** [comment]
I don't know what's going on with Mek cables, but it's on there side.

You can use a power cube as a buffer, or if you have Tesla installed you can use Tesla Generator module instead of Flux Generator and the cables work with it.

See #132 and aidancbrady/Mekanism#4188.
