### ISSUE TITLE
Flux Generator doesn't support Xnet connector 

### ISSUE THREAD

**Issue by Mohron** [bdew-minecraft/generators#137]
Adv Gens: generators-0.9.20.5-mc1.11.2
Xnet: xnet-1.1.5
McJty: mcjtylib-1.1x-2.3.11
Compat: compatlayer-1.11.2-0.2.5

[Xnet Issue](https://github.com/McJty/XNet/issues/51) 

The Xnet connector will not connect to Advanced Generator's Flux Generator. It will however work with an RF tools Powercell.

Steps to reproduce:

- Setup an Adv Generators multiblock with Flux Generator
- Try to connect a Xnet connector to the Flux Generator

**Comment by bdew** [comment]
Use the Forge Energy Emitter module instead, it works.
