### ISSUE TITLE
1.10.2 bdew RF generator not working with bdew generators

### ISSUE THREAD

**Issue by gp009** [bdew-minecraft/generators#138]
just like the title says, RF generator doesnt work, not even showing up in output configuration window
, but visually  its attached seamlessly indicating its part of multi-block structure.

running: 

forge 12.18.3.2185  ( 1.10.2 )

bdew lib 1.12.4.24
adv generators  0.9.20.23

Edit:

I dont know if it was intended but RF generator only works when you place it right next to the turbine controller BUT it works now.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
