### ISSUE TITLE
IC2 features not working with Minecraft 1.11.2

### ISSUE THREAD

**Issue by VampireValik** [bdew-minecraft/generators#139]
- Minecraft: 1.11.2
- Forge: 13.20.0.2284 (and 13.20.0.2282)
- Advanced Generators: Advanced Generators 0.9.20.5 (MC 1.11.2).jar
- IC2: industrialcraft-2-2.7.12-ex111.jar

It seems Advanced Generators isn't seeing IC2 stuff under 1.11.2. JEI doesn't show any of the IC2-specific features like the Advanced Alloy turbines or the EU emitters. Recipes that have an IC2 version (like the capacitors) are using the vanilla version instead of the IC2 version.

**Comment by sandalle** [comment]
During server load, I see:
`[advgenerators/advgenerators]: IC2 Version: NOT FOUND`

Yet I have similar setup to @VampireValik .

- Minecraft 1.11.2
- Forge Mod Loader 1.11.2-13.20.0.2296
- Advanced Generators 0.9.20.5-mc1.11.2
- BDLib 1.13.2.7-mc1.11.2
- Industrial Craft 2 (Experimental) 2-2.7.12-ex111

Might be related to https://github.com/bdew/generators/issues/99, where IC2 support was added back into the Advanced Generators release for 1.9.4.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
