### ISSUE TITLE
Buildcraft fuel still isn't being accepted by the generator (0.9.6)

### ISSUE THREAD

**Issue by slawr34** [bdew-minecraft/generators#14]
Title says it all, fuel simply will not input into a generator. Forestry fuels (i.e. ethanol) work though.

**Comment by bdew** [comment]
Probably you have a mod that includes BC 6.0 API in it's jar. If you post your log i can tell you which one it is.

**Comment by slawr34** [comment]
Looks like my notifications are broken, sorry for the wait.

Here's a pastebin of my modlist:

http://pastebin.com/yb40Y3sY

**Comment by bdew** [comment]
I need the full log (/logs/fml-client-latest.log), upload it to dropbox or some file hosting if it's too big for pastebin.

**Comment by slawr34** [comment]
Here you go

https://www.dropbox.com/s/305hcscqebwafqa/fml-client-latest.log?dl=0

**Comment by bdew** [comment]
Wait what? According to the log fuel is registered correctly

> [13:53:41] [Client thread/INFO] [advgenerators/advgenerators]: Turbine fuels:
> [13:53:41] [Client thread/INFO] [advgenerators/advgenerators]:  \* biofuel: 80 MJ/MB
> [13:53:41] [Client thread/INFO] [advgenerators/advgenerators]:  \* bioethanol: 80 MJ/MB
> [13:53:41] [Client thread/INFO] [advgenerators/advgenerators]:  \* fire_water: 120 MJ/MB
> [13:53:41] [Client thread/INFO] [advgenerators/advgenerators]:  \* rocket_fuel: 112 MJ/MB
> [13:53:41] [Client thread/INFO] [advgenerators/advgenerators]:  \* coal: 100 MJ/MB
> [13:53:41] [Client thread/INFO] [advgenerators/advgenerators]:  \* fuel: 150 MJ/MB

**Comment by slawr34** [comment]
I've just tried the same modlist with new configs and a new world and fuel is working correctly.
