### ISSUE TITLE
Mod registers wrong recipes for EnderIO

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/generators#141]
Hello, @bdew.
I found one old simple bug in Advanced Generators: this mod incorrectly registers recipes for Alloy Smelter.
When there is statement in configuration like this:
```
enderio-smelt: $A + $B * 10 + 1000 RF => $C + 0 xp
```
mod just *__ignores__* amount of items (if item isn't defined with OreDictionary).
In another words, in all versions of Advanced Generators (1.7+, 1.10+) there is missing this code:
```
 number={count.toString}
```
here:
https://github.com/bdew/generators/blob/mc-1.7.10/src/net/bdew/generators/compat/EnderIOXmlEncoder.scala#L32
https://github.com/bdew/generators/blob/mc1.10.2/src/net/bdew/generators/compat/EnderIOXmlEncoder.scala#L32

Please, fix this bug for all versions.
*Thank you for your work!*

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
