### ISSUE TITLE
AdvGen 0.9.20 Server issue

### ISSUE THREAD

**Issue by SirFell** [bdew-minecraft/generators#142]
Yesterday got server to start fine, but it wouldnt respond to any commands or player connection packets, interesting enough it would respond to shadowfact's discordchat mod commands (except !exec), Ive figured out that one of region files were causing some kind of error, so i looked what that region is, happend to be base of only person on the server that uses AdvGen, so i tried removing it which worked.

Dont have any crash logs as server doesnt crash and works 'fine'.

I can guess that it could be that adv generator was built on multiple chunks (had issues with multiblocks being built like that in GregTech before). Could also be that base was located partially in spawn region, so maybe partially loaded generator?

Modpack that gave error: ATM2 v.68 Havent tested without foamfix, since havent had time to do so, sorry.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
