### ISSUE TITLE
Syngas Producer: Unable to Accept Extreme Carbon Values

### ISSUE THREAD

**Issue by Mohron** [bdew-minecraft/generators#143]
- forge-1.11.2-13.20.0.2299-universal
- generators-0.9.20.5-mc1.11.2
- bdlib-1.13.2.7-mc1.11.2
- Calculator-1.11.2-4.0.0

Calculator adds a few additional fuels to the game of varying strength including their ultimate fuel, Controlled Fuel, that has a carbon value of 80,000.  I configured AdvGens to support these fuels and others but even though controlled fuel is listed in the config, it is the only fuel that still doesn't work. This had led me to believe that there is an undocumented max carbon value that the SynGas producer can consume. Is there a way to correct this so that Controlled Fuel can be supported when configured?

Config:
```
recipes {
    if HaveMod calculator {
        carbon-value: I:calculator:coaldust => 1000
        carbon-value: I:calculator:enrichedcoal => 5000
        carbon-value: I:calculator:purifiedcoal => 10000
        carbon-value: I:calculator:firecoal => 25000
        carbon-value: I:calculator:controlledfuel => 80000
    }

    if HaveMod terraqueous {
        carbon-value: OD:dustTinyBurnium => 700
        carbon-value: OD:dustBurnium => 2800
        carbon-value: OD:gemBurnium => 3000
        carbon-value: OD:blockBurnium => 30000
    }
}
```

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Comment by Mohron** [comment]
I've verified this is still an issue. The fuels, in this case, are ProjectE's and Mystical Agriculture's.

- generators-0.9.20.12-mc1.12.2
- bdlib-1.14.3.12-mc1.12.2

Custom Carbon Values:
```
recipes {
    if HaveMod mysticalagriculture {
        carbon-value: I:mysticalagriculture:coal@0 => 2400
        carbon-value: I:mysticalagriculture:coal@1 => 4800
        carbon-value: I:mysticalagriculture:coal@2 => 9600
        carbon-value: I:mysticalagriculture:coal@3 => 19200
        carbon-value: I:mysticalagriculture:coal@4 => 38400
        carbon-value: I:mysticalagriculture:coal_block@0 => 21600
        carbon-value: I:mysticalagriculture:coal_block@1 => 43200
        carbon-value: I:mysticalagriculture:coal_block@2 => 86400
        carbon-value: I:mysticalagriculture:coal_block@3 => 172800
        carbon-value: I:mysticalagriculture:coal_block@4 => 345600
    }
    if HaveMod projecte {
        carbon-value: I:projecte:"item.pe_fuel"@0 => 6400
        carbon-value: I:projecte:"item.pe_fuel"@1 => 25600
        carbon-value: I:projecte:"item.pe_fuel"@2 => 102400
        carbon-value: I:projecte:fuel_block@0 => 57600
        carbon-value: I:projecte:fuel_block@1 => 230400
        carbon-value: I:projecte:fuel_block@2 => 921600
    }
}
```

![image](https://user-images.githubusercontent.com/3623122/35476516-df5c3c38-0376-11e8-9f6d-a1fbbe0e03ca.png)

**Comment by Mohron** [comment]
Not exactly how I'd like to fix this but I found that changing the internal tank capacity will "fix" this issue:

```
cfg Machines {
    cfg SyngasController {
        InternalTankCapacity = 1024000 // Fixes high carbon value fuels
    }
}
```

IMO, it would be better if the tank capacity was controlled by a block that's added to the multiblock structure.
