### ISSUE TITLE
Can't insert Ethylene

### ISSUE THREAD

**Issue by SonOfDiablo** [bdew-minecraft/generators#145]
I just spend a lot of time setting up infrastructure for Ethylene production (in Mekanism) but now I can't pipe it into the Gas Turbine Generator...

Minecraft 1.11.2
BdLib 1.13.2.7
Advanced Generators 0.9.20.5
Mekanism 9.3.2.307
Forge 13.20.0.2315

**Comment by Redblade21** [comment]
Maybe related. Per wiki a _Gas Intake Valve_ is required for Mekanism gasses. As of right now That item is not showing up in JEI or in creative mode. Not reimplemented Yet?
Playing:
Minecraft 1.11.2
All the Mods 2 V0.70
Advanced Generators 0.9.20.5
Mekanism 9.3.2.309

**Comment by PessimisticBastard** [comment]
I know this post is months old, but just so you know; in order for ethylene to be used, it has to be turned into liquid ethylene via a rotary condensentrator.

**Comment by Chefbarbie** [comment]
This is for all the mods 3 version 3.3, Same issue as OP. Using gas intake and ethylene gas (converts to liquid via the generator) and it just sits there. 

SS for proof:https://imgur.com/a/hSiO9

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
