### ISSUE TITLE
1.11.2 server crash - client call

### ISSUE THREAD

**Issue by Terpo** [bdew-minecraft/generators#147]
https://gist.github.com/Terpo/97cc40008a78da7953886544fe80927f
bdlib-1.13.1.4-mc1.11.2.jar
generators-0.9.20.6-mc1.11.2.jar

Crash happened when I was trying to open the GUI of a turbine generator.

**Comment by bdew** [comment]
Your bdlib is outdated, update to the latest version for 1.11.2 and it'll fix it i think.

https://minecraft.curseforge.com/projects/bdlib/files/2392618

**Comment by Terpo** [comment]
wow, ok.... thats kind of interesting as there were six modpack updates since april. I will try the new version, ty
