### ISSUE TITLE
Actually Additions Tier 2 Canola Oil changed internal name

### ISSUE THREAD

**Issue by davqvist** [bdew-minecraft/generators#148]
MC 1.12.1
Forge 2446
AdvGen 0.9.20.4

Just wanting to let you know that in 1.12 (maybe in 1.11 as well?) Actually Additions changed the internal name of the Tier 2 Oil to "refinedcanolaoil" meaning that it currently doesn't work in the Turbines. I can override it in the mean time, but it would be nice, if you could adjust that as well.

**Comment by ChilledDayz** [comment]
Quick question how do I go about overriding this problem. I'm having the same issue. Thanks

**Comment by bdew** [comment]
Sorry for the delay addressing this.

I looked at current AA version, and it looks to me like it uses

* canolaoil (t1)
* crystaloil (t2)
* empoweredoil (t3)

I'm fixing the t1 id, but the t2 one seems right to me unless i'm missing something?

**Comment by bdew** [comment]
Oops, i'm confused, disregard my last comment. i think it goes...

* canolaoil (raw / t1)
* refinedcanolaoil (t2)
* crystaloil (t3)
* empoweredoil (t4)

Will chang accordingly.
