### ISSUE TITLE
no pipe connecting to the generator

### ISSUE THREAD

**Issue by zortag** [bdew-minecraft/generators#15]
i have installed in my modpack generators-mc1710-0.9.6.27.jar and buildcraft-6.2.6.jar plus some other mods that interact each other with no issues (all updated to the latest versions)
the problem is that no one pipe (BC, ender io, extra utilities, tubes) connect to the generator.
i built a 14 pieces generator with 1 controller, 1 HV emitter, 8 turbines and 4 tanks, it is enabled (the machine is surrounded by the gray line and textures are connected), i can access the gui and select the redstone behaviour, but i can't refuel it

**Comment by bdew** [comment]
HV emitters are for IC2. You need to put a Flux Generator module for RF and you need a fluid intake valve to pump fuel in.

**Comment by zortag** [comment]
i know about hv emitters, i need ic2 power.
thanks for explanation about the valve, the wiki need a little expansion
