### ISSUE TITLE
Item Output Port on Heat Generator doesn't output to either Mekanism logistic pipes or RefinedStorage importer

### ISSUE THREAD

**Issue by ab9rf** [bdew-minecraft/generators#152]
The only way I've found, with the mods I have at least, to get the obsidian out of a heat generator is a vanilla hopper. This wasn't the case in prior versions, so something has changed.

MC 1.12.1
Forge 1.12.1-14.22.1.2485
bdlib 1.14.2.8-mc1.12.1
generators 0.9.20.7-mc1.12.1

**Comment by bdew** [comment]
It outputs to things that actually have an inventory, or implement the right capability, you can use a RS interface, or a chest/barrel/drawer/crate/etc as a buffer and then an importer on it. That's pretty much how it always worked.
