### ISSUE TITLE
1.10.2 Marble and Basalt texture disapears

### ISSUE THREAD

**Issue by Arsomang** [bdew-minecraft/generators#153]
Marble and Basalt textures disappears after opening config window in Advanced Generators witch also causes client crash when JEI tries to pull a texture for these materials. Placing one of these materials and breaking them restores texture and prevents crash in JEI. But frustrating trying to remember to do that every time you open the Generators Config window.

**Comment by bdew** [comment]
That's... odd. I'll look into it.

**Comment by bdew** [comment]
I have a fix for 1.12, this will be included in the next version of BDLib.

I've decided against doing updates for this for older versions of minecraft for now since it's a minor visual glitch. If at some point i'll do updates for more serious issue i'll add this along.

**Comment by Arsomang** [comment]
It causes client crashes so i feel its more then visuale. If you have
marble or basalt come up in jei when the textures are missing cluent
crashes.

**Comment by bdew** [comment]
Can you post an example of a crash? I only seen the disappearing glitch.

**Comment by Arsomang** [comment]
Not home but when you get the textures to disapear. Then do a search for
marble and basalt and you will crash

**Comment by bdew** [comment]
Doesn't happen in 1.12... i'll try in earlier versions later.

**Comment by bdew** [comment]
I've tried searching for marble in JEI while it's in the glitched invisible state in 1.10.2/1.11.2/1.12.2 and don't see a crash.

Regardless i've decided to do an update for 1.10.2 and 1.11.2 as well which will be out later today.
