### ISSUE TITLE
Question about configuration

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/generators#154]
Hello, @bdew !
I've a question about configuraion of Advanced Generators.
Does custom turbine materials require additional model/blockstate files along with textures and localization? Can't find information about it.
I want to use the most power from this cool mod and main it's feature - custom turbines. So I need help with it.
Also, please, update documentation abount configuration on your site (It would be helpful for me and other modpack makers).

Thank you *very much* for your work!

**Comment by bdew** [comment]
Yes you need to add blockstate and textures for the turbine block and model for the related items (turbine and upgrade kit) if they are enabled and localization for everything.

Example of blockstate - https://github.com/bdew/generators/blob/mc1.12/resources/assets/advgenerators/blockstates/turbine_bronze.json

Note that you need to use the special model "advgenerators:sided_multiblock.extended" and pass in the textures.

And yes i'm aware that the documentation sorely needs an update, i hope to find time for it sometime soon.

**Comment by OneEyeMaker** [comment]
@bdew 
Thank you very much!
