### ISSUE TITLE
IC2 steam not being accepted by Steam Generator

### ISSUE THREAD

**Issue by ajwalters95** [bdew-minecraft/generators#155]
Steam generated from the Industrial Craft 2 Steam Boiler is not being accepted as a valid fuel source for the Steam Generator.

Is this intended behavior?

Mod Version - generators-0.9.20.7-mc1.12.1.jar

**Comment by bdew** [comment]
IC2 steam intentionally has a different ID set by IC2 that makes it not work with anything else.

I am considering allowing IC2 steam to be used in heat exchangers to make normal steam (and turn into IC2 distilled water), tho it's kinda silly. And tricky to balance right.

If you are using an IC2 fluid reactor you can also pipe the hot coolant directly to a heat exchanger to make normal steam (and skip the ic2 steam step entirely).

**Comment by ajwalters95** [comment]
I noticed it was a different ID and I figured there was a reason you didn't have it included. Thanks for the response
