### ISSUE TITLE
The turn off on redstone setting for EU 

### ISSUE THREAD

**Issue by Arsomang** [bdew-minecraft/generators#156]
The EU High Voltage Emitter config to turn off with redstone signal randomly turns back to always on.
I am using Advanced Generators Version 0.9.20.23 For Minecraft 1.10.2

**Comment by bdew** [comment]
I'm not working on 1.10 versions anymore, unless it's a critical bug (which this doesn't seems like one).

Does it happen in modern versions of AG and IC2?

**Comment by Arsomang** [comment]
Why do you consider 1.10 and old version it is the version that 90 % of the mods are stable on now and all the streamers and youtubers  playing mod packs are playing 1.10 cause it is the one with the most mods complete I would think if you want a good name for yourself you would want to keep the most currently played version bug free. And if you look at all the other major mods out there like Mekanisum, Storage Drawer, Applied Enerjistics, and many more they are still bug fixing 1.10. Even the Texture packs do not have newer then 1.10 ready yet to be considered release versions.

**Comment by InThayne** [comment]
Having the same problem using the eu extreme voltage emitter.  The output config at times, resets from 'enable on redstone' to 'always on'.  This results in loss of power to the RF machinery that is supplying fuel for the gen system, which ultimately shuts down.  Using the latest Age of Engineering release.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
