### ISSUE TITLE
Can I share this mod in China

### ISSUE THREAD

**Issue by 6Bpencle** [bdew-minecraft/generators#158]
The mod is very interesting ,I very like it.I think you can do it better.So I want to share this mod with the minecraft forum in China.This is website [mcbbs](http://www.mcbbs.net),and let more friends use it.I hope you can agree!

**Comment by bdew** [comment]
Yes you can, according to the [license](https://github.com/bdew/generators/blob/mc1.10.2/MMPL-1.0.txt). No need to ask me.
