### ISSUE TITLE
client render crash 1.12.2

### ISSUE THREAD

**Issue by unstablecraft** [bdew-minecraft/generators#161]
Mod Version: Advanced Generators 0.9.20.9 (MC 1.12.2)
Java: java8
Forge: forge-1.12.2-14.23.1.2555-universal.jar

https://pastebin.com/LDZF80QH Crash-report

this happens when you are in creative and pick it out jei and drop it in your inv

jei give this error : http://prntscr.com/hhrx9h

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
