### ISSUE TITLE
Crash on load [1.12.2]

### ISSUE THREAD

**Issue by LunaSquee** [bdew-minecraft/generators#164]
Mod crashes with
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Advanced Generators (advgenerators)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/event/FMLInterModComms$IMCEvent
```
Full crash report: https://termbin.lunasqu.ee/bl9o

forge-1.12.2-14.23.1.2566
bdlib-1.14.3.10-mc1.12.2
generators-0.9.20.10-mc1.12.2

If it's just a mod conflict, I'm terribly sorry for wasting your time.

**Comment by ChloeDawn** [comment]
Does it still crash when you remove Advanced Generators and BDLib? Please provide your client game log too.

**Comment by bdew** [comment]
That error doesn't make any sense whatsoever. cpw/mods/fml hasn't been a thing in long while and there are no references to that package anywhere in my code AFAIA.

Can you post the full log file please?

**Comment by LunaSquee** [comment]
No, it only crashes when I include the generators mod.
Here's the full fml log, it's massive but if you think it'll be of any help: https://termbin.lunasqu.ee/wyr9

**Comment by LunaSquee** [comment]
It seems to work without any other mod though, so I'm guessing it's a conflict but I cannot find what mod would be causing it in the logs

**Comment by LunaSquee** [comment]
Figured it out, I'm a dummy. I apparently had a 1.7.10 version jar of the mod in my mods directory as well
```
[15:31:21] [main/DEBUG] [FML/]: Examining for coremod candidacy generators-0.9.20.123-mc1.7.10.jar
[15:31:21] [main/DEBUG] [FML/]: Not found coremod data in generators-0.9.20.123-mc1.7.10.jar
```
I'm surprised that forge is unable to inform me of that. I'm very sorry for wasting your time.
