### ISSUE TITLE
Custom turbines not showing on JEI

### ISSUE THREAD

**Issue by EverNife** [bdew-minecraft/generators#165]
When on MULTIPLAYER, the custom turbine are not showing on JEI

![image](https://user-images.githubusercontent.com/11357801/34473503-b566ee08-ef5a-11e7-8b9c-245b40166129.png)

(On single player they show ok)

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.

**Comment by EverNife** [comment]
👍
