### ISSUE TITLE
Generators blocks (turbines, valves, etc) disappear when pick up with a pickaxe

### ISSUE THREAD

**Issue by jonabrv1965** [bdew-minecraft/generators#167]
When removed with a pickaxe, almost all mod blocks (turbines, valves, addons) not appear in the inventory. They simply disapper...  (Did not try with the controller itself). 

The generator controller, once running, keeps working like if no block were removed until you reload the world (save and load at that moment).

generators-0.9.20.12-mc1.12.2
bdlib-1.14.3.11-mc1.12.2
forge 2575

**Comment by bdew** [comment]
Bug in my last version of BDLib, fixed in 1.14.3.12.
