### ISSUE TITLE
Immersive Petroleum Gasoline is too weak.

### ISSUE THREAD

**Issue by IMarvinTPA** [bdew-minecraft/generators#168]
IP's Gasoline, when compared to what it does for Thermal Expansion is vastly too weak.
TE gives 1.2m RF/B
AG gives 50k RF/B.

Suggest boosting it up to just a hair under Naphtha.

IMarv

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
