### ISSUE TITLE
Texture conflict with Extream Reactors

### ISSUE THREAD

**Issue by Dente222** [bdew-minecraft/generators#169]
There is a small steam texture conflict between Extreme Reactors and Adv Generators
it changes the steam texture in steam turbine into black/purple missing texture

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
