### ISSUE TITLE
BC Fuel problem

### ISSUE THREAD

**Issue by MinoCraft** [bdew-minecraft/generators#17]
Hello,

After a reboot of my server, the turbine can't accept buildcraft fuel as you can see in this pictures:
https://imgur.com/a/3vX4V
https://imgur.com/a/NQjne 
I am obliged to start again the server so that the turbine works
Otherwise advanced generator is awesome !
An other point, turbine take a huge amount of update time (between 100 and 150 μs)
Thank in advance !

**Comment by bdew** [comment]
Sorry i somehow missed this bug report.

Please post your log from the server from a run where it doesn't work.

Also to be clear: just restarting again fixes it?

**Comment by MinoCraft** [comment]
Hello,
Sorry for the time to answer, but with my job I did not have time to answer before.
I tested in solo with the last version of advanced generators and the problem is present yet ! But it occurs only with BC fuel (there is not of log in the console on the problem)
And yes, just restarting again to fixe it ! 
I do not really know how can I help you ?
Thank in advance !

**Comment by bdew** [comment]
Upload your full fml log (logs/fml-server-latest.log) from a run where it doesn't work and a run where it does.

**Comment by MinoCraft** [comment]
At present I have the problem and to solve it I use MFR Biofuel.
I uploaded the lastest fml server log as asked:
https://www.dropbox.com/s/8bxydb17lp2ngpx/fml-server-latest.log?dl=0

Thank you for your help !

**Comment by bdew** [comment]
> [21:01:02] [Server thread/DEBUG] [FML/]:  BuildCraftAPI|fuels(API: BuildCraftAPI|fuels:1.0): binnie-mods.jar ()

Your binnie-mods includes an outdated version of BuildCraft fuels API which makes my mod unable to detect BC fuel as a valid fuel for turbines. Try updating it.

Also your buildcraft is outdated, the current version of Advanced Generators was only tested with 6.3.x so i would recommend updating that as well.

**Comment by estebes** [comment]
Is this issue still happening? Because i updated both mods yesterday to their latest version and it was working fine but today its not working. without changing anything. really strange

**Comment by bdew** [comment]
If you still have a mod with the old BC API bundled with it - it will happen. I'm not sure why sometimes it works, possibly different load order that gets the right API version loaded first?

Look for "BuildCraftAPI|fuels:1.0" in your log (that's the outdated version) and it should say what jar it came from. Or upload your logs and link them here.

**Comment by estebes** [comment]
BuildCraftAPI|fuels(API: BuildCraftAPI|fuels:1.0): Railcraft_1.7.10-9.4.0.0-DNS.jar () apparently is this (custom?) version of railcraft in the pack

**Comment by estebes** [comment]
updating to railcraft 9.5 should fix it

**Comment by bdew** [comment]
New version of BDLib includes the versions of all loaded APIs and what mod they are loaded from.
If anyone is still having this problem - open your log, look for 

> \* BuildCraftAPI|fuels (1.0) from <**modname**>.jar

And go bug the author of that mod.

**Comment by estebes** [comment]
Havent had this problem since i updated railcraft but cool stuff
