### ISSUE TITLE
[1.12.2] Machine Data Port has no texture

### ISSUE THREAD

**Issue by SnowShock35** [bdew-minecraft/generators#170]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.2.2618
- BdLib 1.14.3.12
- Advanced Generators 0.9.20.12

#### Issue Description

As explained clearly in the title of the issue, the texture for the machine data port isn't found and displays the missing block texture.

#### Issue Media

![Issue Media #1](https://ss.snowshock35.com/2018/02/1519157933-f790fc55.png)
![Issue Media #2](https://ss.snowshock35.com/2018/02/1519157940-d422c1f1.png)
![Issue Media #3](https://ss.snowshock35.com/2018/02/1519157961-4e75fe6e.png)

**Comment by citybuilder45** [comment]
In generators-0.9.20.12-mc1.12.2.jar\assets\advgenerators\blockstates\generators_data_port.json, for "model" it is "pressure:sided_multiblock.extended". Changing that to "advgenerators:sided_multiblock.extended" fixes it.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
