### ISSUE TITLE
Suggestion: Thermal Expansion Tree Oil and other fuels

### ISSUE THREAD

**Issue by TheDarkPreacher** [bdew-minecraft/generators#171]
Using the latest version of Thermal Expansion and Advanced Generators, I noticed that the TE Tree Oil would not go into a gas turbine. Liquifacted coal works, but Tree oil does not. Not sure if the other TE fuel types that have been added in 1.12.2 will also work with AG (Tree oil, Refined Fuel, crude oil, creosote, basically anything that will burn in a TE compression dynamo.) I suggest that the same fuels that work in the Compression dynamo should also work with the gas turbine.

**Comment by levicc00123** [comment]
Thank you!

**Comment by Saklad5** [comment]
Note that Creosote [has been buffed](https://github.com/CoFH/ThermalExpansion/commit/b249a91377b55398b8f74f393b281542d98c6785) in the development version of Thermal Expansion, so if you are hard-coding the RF value of fuels that should be accounted for.

**Comment by MasterEnderman** [comment]
You can use the config files to add more fuels to the turbines.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
