### ISSUE TITLE
ChiselsAndBits conflict

### ISSUE THREAD

**Issue by TechnicJelle** [bdew-minecraft/generators#172]
In my serverlog it says "[chiselsandbits]: Unable to determine blocks eligibility for chiseling" for some of the blocks in the mod.
I read up on the error (https://github.com/AlgorithmX2/Chisels-and-Bits/issues/49) and it seems it can't be fixed by @AlgorithmX2.
These are the blocks:
net.bdew.generators.modules.efficiency.BlockEfficiencyUpgradeTier2$ attempted to load net/minecraft/client/util/ITooltipFlag
net.bdew.generators.modules.turbine.BlockTurbine attempted to load net/minecraft/client/util/ITooltipFlag
net.bdew.generators.modules.powerCapacitor.BlockPowerCapacitor attempted to load net/minecraft/client/util/ITooltipFlag

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
