### ISSUE TITLE
Crash On Loading

### ISSUE THREAD

**Issue by CyberShroom** [bdew-minecraft/generators#173]
My minecraft keeps crashing when it finishes 2 on load screen. Its because of Advanced Generators. Can you fix this?
BdLib: 1.14.3.12
Adv. Gen.: 0.9.20.12
Forge: 14.23.2.2627
I also updated java but I cant figure out how to fix this.

**Comment by CyberShroom** [comment]
Would having NVIDIA GT 635 have anything to do with it?

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
