### ISSUE TITLE
Actually Additions Canola oil too weak

### ISSUE THREAD

**Issue by repvik** [bdew-minecraft/generators#174]
I built a generator with 5 manyullyn turbines, air/gas mixer and gas mix compressor. With Empowered canola oil (4th tier oil), this gives me 2500RF/t, using ~1.93mB/t. 
This provides  approx. 1295RF/mB. 

However, using a bog-standard oil generator (200RF/t for 800t, using 50mB) generates 3200RF/mB.

For the refined tiers of oil:

Simple oil generator output pr. mB:
refined: 120/240 = 576RF/mB
crystallized: 160/560 = 1792RF/mB
empowered: 200/800 = 3200RF/mB

Advanced generators output pr. mB:
refined: 6,8mB/t = 368RF/mB 
crystallized: 3,4mB/t = 735RF/mB
empowered: 1,93mB/t = 1295RF/mB

Output as percentage of oil generator output:

Refined: 63%
Crystallized: 41%
Empowered: 40%

Suggest setting empowered oil output to the following:

Refined canola oil: 600RF/mB
Crystallized canola oil: 1800RF/mB
Empowered canola oil: 3200RF/mB

This will put a basic gas generator without upgrades at the same baseline as a simple oil generator.

**Comment by repvik** [comment]
Patch adjusting canola values to equal those of oil generators: https://gist.github.com/repvik/6a7822ff503bea150fdf1897af8f1355

Edit: Updated gist to correct branch.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
