### ISSUE TITLE
Game/server crashes if you attempt to remove a machine part with a sticky piston

### ISSUE THREAD

**Issue by DustinStuff** [bdew-minecraft/generators#176]
Steps to reproduce: Make a complete generator and remove a part with a sticky piston, the game crashes (but doesn't corrupt the world, fortunately).

Workaround: Don't do this.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
