### ISSUE TITLE
[Request] Add biocoal from Actually Additions as coal source

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/generators#177]
Tittle says most of it, add bio coal from actually additions as coal source... to be honest I would love to see options for fuels and coals in a config file so we don't have to bother you and we can just add the coals and fuels options from other mods, and we can balance how much each fuel produces in order to balance our server, but that is another request for a future release XD, for now just adding bio coal to the list would be great.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
