### ISSUE TITLE
[request] Add molten uranium (immersive engineering) as heat source for heat exchanger

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/generators#178]
Well, currently I have no user for uranium, I have a ton of it on the server, everyone has a ton of it on the server and no one has uses for all that uranium other than the thermo-electric  generator from Immersive Engineering, which only uses 1 block or uranium and that's it... So since the motel uranium can be acquired quite easily with tinkers, could you add it as a heat source for the heat exchanger?

The uranium block in Immersive engineering is rated at 2000K when lava is at 1000K so it could be a nice upgrade since uranium is not as common as lava in the world, but since we have plenty of it and no use for it, it could make your generator a great user of this liquid.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
