### ISSUE TITLE
Advanced pressure  valve has no recipe 

### ISSUE THREAD

**Issue by FallenRecruit** [bdew-minecraft/generators#179]
Like title says the item has no recipe even if I have Ender IO and Thermal expansion

**Comment by Fatmice** [comment]
Yes, I confirm

**Comment by PaladinNight** [comment]
It appears that the smelter based recipes for the advanced pressure value are incorrect:
      if ((HaveMod ic2 || HaveMod thermalexpansion) || HaveMod EnderIO) {
            if HaveMod EnderIO {
                enderio-smelt: $V + OD:ingotVibrantAlloy * 8 + 50000 RF => $A
            }

            if HaveMod thermalexpansion {
                TE-smelt: $V + OD:ingotEnderium * 8 + 48000 RF => $A
            }

            if HaveMod ic2 {
                X = I:ic2:crafting@3 // Advanced alloy

                XXX
                XVX => $A
                XXX
            }

The ic2 does work, but both of the smelt options do not.

**Comment by Enilo** [comment]
I have the same problem, if I have IC2 installed there is that recipe but without that mod added the recipe can't be crafted at all.

**Comment by Forsari0** [comment]
Use this CraftTweaker snippet to add default recipe:
```recipes.addShaped(<advgenerators:advanced_pressure_valve>, [[<minecraft:ender_pearl>, <minecraft:gold_ingot>, <minecraft:ender_pearl>], [<minecraft:gold_ingot>, <advgenerators:pressure_valve>, <minecraft:gold_ingot>], [<minecraft:ender_pearl>, <minecraft:gold_ingot>, <minecraft:ender_pearl>]]);```

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
