### ISSUE TITLE
Crash after updating to bdlib-mc1710-1.6.0.36

### ISSUE THREAD

**Issue by Staegrin** [bdew-minecraft/generators#18]
After updating to the new bdlib so my game would be compatible for the new forestry my game crashes. Without generators installed no crash, with it installed I get a crash.

crashlog:
http://pastebin.com/CYEFiGNR
fml log:
https://gist.github.com/Staegrin/82c71f8c9e4c32e7da73

**Comment by bdew** [comment]
0.9.6 is incompatible with bdlib 1.6.0
either grab 0.9.7 from [jenkins](http://jenkins.bdew.net/job/generators-1.7.10/) (but there is some unfinished stuff there) or wait for a new release soon(tm)

[For more details read this](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2189255-advanced-generators-v0-9-6-freeform-multiblock?comment=132)
