### ISSUE TITLE
Energy value read by OC is one digit short of the actual value in the generator

### ISSUE THREAD

**Issue by Fatmice** [bdew-minecraft/generators#180]
Per title.
The digit read is only 8 digits long whereas the value stored in the generator is 9 digits long.  Thus the tens place is missing.

MC: 1.12.2
Advanced Generator: 0.9.20.12
OC: 1.7.2.67

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
