### ISSUE TITLE
Extra Utilities Redcoal useful in syngas producer?

### ISSUE THREAD

**Issue by DoomSquirter** [bdew-minecraft/generators#181]
so exu redcoal doesn't increase the carbon value but instead boosts the efficiency based on your GP some way behind the scenes.  The tooltip shows 1600 carbon value tho.

does that mean it's equivalent to charcoal/coal then and probably not worth using in syngas production?

any way I could tell if it's actually giving me more burn time within advanced gens or just assume the tooltip carbon value is correct?

generators-0.9.20.12-mc1.12.2

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
