### ISSUE TITLE
AdvGen detects metals but wont add turbine recipes

### ISSUE THREAD

**Issue by GamertechAU** [bdew-minecraft/generators#184]
MC - 1.12.2
AG version - 0.9.20.12
bdlib version - 1.14.3.12

Advanced Generators correctly detects iron, gold, bronze, steel and enderium ingots, but only adds iron and gold turbines.

Debug shows the metals properly detected, but can't create the turbine blade recipe.

Bronze and steel are added by Mekanism, enderium by FunOres.

https://pastebin.com/6tgucUY6

**Comment by TheSnowyChickens** [comment]
Jip, same problem here.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
