### ISSUE TITLE
Steam Turbine Bug

### ISSUE THREAD

**Issue by Redrabbitsama** [bdew-minecraft/generators#185]
MC: 1.12.2
AG: 0.9.20.12

The Steam Turbine consumes steam even if it is not producing energy.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
