### ISSUE TITLE
Recipe conflict with Thermal Foundation iron gear

### ISSUE THREAD

**Issue by altDark** [bdew-minecraft/generators#187]

**Comment by altDark** [comment]
Hi,
there is conflict between Thermal Foundation iron gear and AG Iron frame.
Versions: 
- ThermalFoundation-1.12.2-2.6.1.22-universal.jar
- generators-0.9.20.12-mc1.12.2.jar

BR
Radek

**Comment by GhEppIO82** [comment]
i have same problem with gear......fix bro :(

**Comment by nexcroblade** [comment]
Please change the recipe to the four corners or add more ways to make it

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.

**Comment by crimso** [comment]
Hello, I would like to reopen the topic, the recipe conflict is stil present in the lates version.
