### ISSUE TITLE
Multiblock structures

### ISSUE THREAD

**Issue by eRko16** [bdew-minecraft/generators#188]
Hello, i just wanted to ask, if its possible to implement that the main blocks of multiblock structures forms aswell with the block itself, its kinda "meh looking" when the multiblock has really nice 3d look and there are "vanilla" blocks inside it for example input plugs, input hatches, output hatches or energy plugs.

Thanks for answer

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
