### ISSUE TITLE
[1.12.2] Every recipe is 2 times in JEI

### ISSUE THREAD

**Issue by TheSnowyChickens** [bdew-minecraft/generators#189]
MC: 1.12.2
Forge: 2815
AG: 0.9.20.12

The title says enough. :)

![grafik](https://user-images.githubusercontent.com/29357962/53700154-bc787600-3def-11e9-8bde-7937036a20a5.png)
And this is with EVERY recipe.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
