### ISSUE TITLE
Adding Steam as a fuel

### ISSUE THREAD

**Issue by slawr34** [bdew-minecraft/generators#19]
Hey bdew,

I looked over you tutorials for adding new fuels to be usable in an advanced generator:

turbine-fuel: {fluidname} {number} MJ/mB

What does 'number' mean in this context? Fluid ID? If so, how can I find the fluid ID for steam?

**Comment by bdew** [comment]
{number} is the energy produced (MJ) per millibucket (mB)

Also 0.9.7 (which is coming out today) has a separate generator for steam :P

**Comment by slawr34** [comment]
Aw man just after I made 27 turbines for my high pressure boiler :P

**Comment by bdew** [comment]
You're in luck, it uses the same turbine blocks but with a different controller.

**Comment by slawr34** [comment]
Oh god, that's a relief. Whats the MJ/mb of steam in that generator?

**Comment by bdew** [comment]
It had a different mechanic where steam amount affects RPM which in turn affects power. It's balanced to end up with ~0.2 MJ/mB.

**Comment by slawr34** [comment]
So more steam = more efficient (and hence more power per tick?).

**Comment by bdew** [comment]
Yeah, pretty much

**Comment by slawr34** [comment]
Sorry to oversimplify it if it was meant to be more complicated. Can you PM me when it's up?

**Comment by bdew** [comment]
http://bdew.net/2015/02/06/advanced-generators-0-9-7-pressure-pipes-1-0-3/
