### ISSUE TITLE
Exception loading model

### ISSUE THREAD

**Issue by bookerthegeek** [bdew-minecraft/generators#190]
# Heyo!
Saw [this](https://gist.github.com/bookerthegeek/f967728c928d75bd240c830d3bf26fc6) in the log. No idea if it breaks anything but though you would want to know. [HERE](https://gist.github.com/bookerthegeek/a0f0b398fe9563af2a6e6ffc3cb87444) is the full mod list.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
