### ISSUE TITLE
Recipes for ic2 compatible stuff doesn't have recipes when ic2 classic is loaded.

### ISSUE THREAD

**Issue by Trinsdar** [bdew-minecraft/generators#191]
Advanced gens 0.9.20.12
Ic2 classic 1.5.4.2

It can be easily fixed by checking for the modid `ic2-classic-spmod` within the ic2 modid check here: 
https://github.com/bdew/generators/blob/mc1.12/resources/assets/advgenerators/config/recipes.cfg#L95

**Comment by abculatter2** [comment]
I would like to second this.
Based on my very limited testing, everything in Advanced Generator's IC2 compatibility would be easily compatible with IC2 classic. It'd just be a matter of setting the default recipes, and it would likely work fine.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
