### ISSUE TITLE
CraftTweaker support

### ISSUE THREAD

**Issue by Rundas01** [bdew-minecraft/generators#192]
Hello,
I want to ask whether this mod has support for CT2.
My plan is adding the oils from Gregtech as a fuel for the Gas Turbine.
Thanks in advance.
Rundas

**Comment by MasterEnderman** [comment]
It doesn't have any CraftTweaker Support. But you are able to add more fuels in the config files. there is a section in the "turbine.cfg" where you can add custom fuels to the turbine.

**Comment by Rundas01** [comment]
@MasterEnderman Took a LONG break from working on the modpack xD.
But I don't see "turbine.cfg" in the config folder at all.
https://drive.google.com/file/d/13bPeoSd3vFDa_pRRreZQa0rvS2DyKx9t/view?usp=sharing
https://drive.google.com/file/d/19q_c5X8ALm1Vo4csvKcSvs3q4k-qyQbl/view?usp=sharing
here are 2 screenshots. the overrides folder is empty.

**Comment by MasterEnderman** [comment]
You need to extract them from the mod jar file and copy them into the override folder. Then your changes override the internal config files.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
