### ISSUE TITLE
Crash when loading save

### ISSUE THREAD

**Issue by grydian** [bdew-minecraft/generators#193]
https://pastebin.com/ZHiZmdh7

The crash mentions a tooltip crash.  I went into the config for advanced gen and turned off the tooltips and I am still crashing.  Any idea how I can fix this?

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
