### ISSUE TITLE
Advanced Generators Duping Gases

### ISSUE THREAD

**Issue by NielsPilgaard** [bdew-minecraft/generators#195]
When Gas is inserted into the Gas Input, the Gas Input ignores the senders `doTransfer` parameter, resulting in the duping of the input gas.

I reported the gas dupe issue on [Mekanism's issue tracker](https://github.com/mekanism/Mekanism/issues/5887) and they believe they found the cause:

> It seems they are implementing handling for our gas incorrectly. In [this line](https://github.com/bdew/generators/blob/mc1.12/src/net/bdew/generators/modules/gasInput/TileGasInput.scala#L34) they are always inserting the gas as a fluid into their machines if they can. This is a mistake, as they are entirely ignoring our `doTransfer` parameter which is used for simulation.

So in essence what they are doing, when we ask their tile to simulate inserting gas (so we can see how much would fit and calculation an even distribution), they are just ignoring the fact it is a simulation, and increasing their contents regardless.

### Versions
- bdlib-1.14.3.12-mc1.12.2
- generators-0.9.20.12-mc1.12.2
- Forge 1.12.2-14.23.5.2847

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
