### ISSUE TITLE
Output Configuration crashes the game

### ISSUE THREAD

**Issue by jsmierzchalski** [bdew-minecraft/generators#196]
Hello. When I open the Output Configuration GUI of Gas Turbine Generator, the game crashes. I'm using Minecraft 1.7.10 and Advanced Generators 0.9.20.123.

[crash-2020-03-28_00.03.42-client.txt](https://github.com/bdew/generators/files/4396280/crash-2020-03-28_00.03.42-client.txt)

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
