### ISSUE TITLE
Syngas does not go in buckets

### ISSUE THREAD

**Issue by Nysterian** [bdew-minecraft/generators#198]
You cannot pick up syngas with a bucket, making it impossible to move around and use it's explosive property like shown in the video without other mods.

I'm running a lightweight personal modpack and I don't want to add any of the other big, usual mods, so being able to move it in a bucket would be nice.

Meanwhile, is there any small mod that allows you to move that fuel around? The video in the syngas page shows you moving it with some sort of canister, but I don't know what mod adds that.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
