### ISSUE TITLE
Crash with the latest Extra Utilities

### ISSUE THREAD

**Issue by CascadingDragon** [bdew-minecraft/generators#2]
Crash report: http://pastebin.com/LH9W4Zuc

Using Extra Utilities 1.1.0i (and 1.1.0g which prompt me to update), Generators 0.9.0.3, BLib 1.4.3.13, and Pressure 0.9.2.8.

I have not touched the configs.

**Comment by bdew** [comment]
Looks like EU includes only some of the BuildCraft API. I'll see how to handle that gracefully.

For now as a workaround, you can install BC or another mod that includes the full API.

**Comment by CascadingDragon** [comment]
Figured as much, but since I'm only pack building, I just thought I'd report it and continue with configs and Minetweaker. Thanks though!

**Comment by bdew** [comment]
Please verify that this fixes the issue ([download here](http://jenkins.bdew.net/job/generators-1.7.10/4/artifact/build/libs/generators-mc1710-0.9.0.4.jar))

**Comment by CascadingDragon** [comment]
Fixed! Thank you very much!
