### ISSUE TITLE
Power gauges tooltips show MJ instead of RF

### ISSUE THREAD

**Issue by Staegrin** [bdew-minecraft/generators#20]
Thanks for all the hard work on your mods.
Upgraded to version generators-mc1710-0.9.7.35 and I'm testing the new options for the generators. The controllers are still showing the stored power in the capacitors as MJ not RF. Sorry to bother you with this, just thought you should be made aware.

![2015-02-07_14 16 41](https://cloud.githubusercontent.com/assets/8494635/6092203/fd9412de-aed3-11e4-9710-358ac85b0193.png)

**Comment by bdew** [comment]
Will fix in next version
