### ISSUE TITLE
[Suggestion] Configurable Steam Turbine Input

### ISSUE THREAD

**Issue by Jerome226** [bdew-minecraft/generators#200]
Could be cool to have a config option to change the tag of the Steam Turbine Input. So instead of "forge:steam" you can change to  what you want.
```
        FluidTags.getAllTags.getTag(new ResourceLocation("forge:steam")),
```
Could be useful for the pack i'm making, thanks!

**Comment by bdew** [comment]
It's a steam turbine, I don't think it needs to be able to accept something else, that would just be confusing.
You could always use the other turbine and register whatever you want to add as a fuel for it.
