### ISSUE TITLE
Gas Burning Turbine generation rate is way too low

### ISSUE THREAD

**Issue by changhe3** [bdew-minecraft/generators#201]
Using hydrogen as example, mekanism gas-burning generator generates about ~15k RF/t if you can keep up with it (~200 mb/t), which is a single block, while a multi-block gas burning turbine with 50 turbine max tier turbines only generates 50k RF/t. It would be great if the multi-block includes something like "combustion chamber", which increases fuel consumption rate and generates more powers accordingly if you can keep it full.

**Comment by bdew** [comment]
"only" 50k RF/t is already a lot unless you are playing with some seriously overpowered mods. Most single block RF generators in other mods produce like 50-200 RF/t (e.g. TE dynamos)
You can always change that in the configs if you want, but i don't think the defaults need to be any higher.

**Comment by changhe3** [comment]
Yeah, changing the config is always an option, but I think it's more flavorful and interesting to adopt the approach that mekanism adopted in 1.16.5, that the fuel chamber has a imaginary "pressure" and more fuel you put in, the faster it burns. 

https://wiki.aidancbrady.com/wiki/Gas-Burning_Generator
