### ISSUE TITLE
When I mistakenly tried to drain a Fluid Intake Valve with a Fluid pipe, the server crashed

### ISSUE THREAD

**Issue by lolosiax** [bdew-minecraft/generators#202]
When I mistakenly tried to drain a Fluid Intake Valve with a Fluid pipe, the server crashed.

This is the Issues when I reported to the author of the Pipez Mod...
[https://github.com/henkelmax/pipez/issues/103](https://github.com/henkelmax/pipez/issues/103)

He was said : Fluids should never be null. No fluid means Fluids.EMPTY
the block is advgenerators:fluid_input

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fluids.FluidStack.getFluid()" because "fluidInTank" is null
	at de.maxhenkel.pipez.blocks.tileentity.types.FluidPipeType.insertEqually(FluidPipeType.java:101)
	... many more

**Comment by bdew** [comment]
That's odd... I'll try to reproduce it and figure out where that null comes from. It should be using EMPTY everywhere.

**Comment by bdew** [comment]
Should be fixed in bdlib

* [BDLib 1.18.2.13 (MC 1.18.1)](https://www.curseforge.com/minecraft/mc-mods/bdlib/files/3712644)
* [BDLib 1.19.0.4 (MC 1.18.2)](https://www.curseforge.com/minecraft/mc-mods/bdlib/files/3712646)
