### ISSUE TITLE
Language provider missing

### ISSUE THREAD

**Issue by BigAl607** [bdew-minecraft/generators#203]
Game version: 1.18.2
Forge version: 40.0.22
Mod version: 1.1.0.3 (1.18.2) 
Modpack: My own

When ever I try to load the, I get the following error

![advgeneror](https://user-images.githubusercontent.com/13182567/159600125-17128b77-0069-43bb-ad4c-39a25c758301.png)

Not sure how to fix it other than removing it, which is unfortunate because I really like the mod.

**Comment by bdew** [comment]
You need to install this dependency - https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force
If you run through curseforge it should have installed it automatically

**Comment by BigAl607** [comment]
Thanks. I'm using the GDLauncher
