### ISSUE TITLE
syngas seems to be un pullable.

### ISSUE THREAD

**Issue by SpiderKraken** [bdew-minecraft/generators#205]
in 1.18.2 there are no tags on syngas so none of the mods avilable with pipe are able to pull the gas other than a mekanism addon for xnet that breaks things and forces you to have mekanism. tags for xnet and other mods to handle syngas would be a viable fix . even pipez cant grab syngas without mekanism.

**Comment by SpiderKraken** [comment]
actually seems to be more to do with specifically power generator machines. i can move syngas and steam as expected with some tricky figuring out but nothing other than mekanism is able to push these into the gas turbine or the steam turbine, the fluid intake doesnt even register the connections with the little red arrows.     for example i can push lava and water into the heat exchanger with xnet. but i cannot get that steam out of there into the steamturbine with the same method using refined storage, pipez or xnet

**Comment by bdew** [comment]
The colored arrows are only used on outputs, not intakes (those aren't directional).
For outputs if they don't appear automatically, you can rightclick that side with a wrench to force it to conenct.

If that doesn't help please provide screenshot or step by step instructions to what's exactly not working.
