### ISSUE TITLE
Custom Fuel Datapack

### ISSUE THREAD

**Issue by pinguino132** [bdew-minecraft/generators#206]
Hello, i'm having trouble trying to add forge:ethanol to a datapack so i can use Immersive Engineering Ethanol and other mods ethanol as fuel for the gas turbine generator.

It's structure data -> minecraft -> advgenerators -> recipes -> fuel -> ethanol.json

{
  "type": "advgenerators:liquid_fuel",
  "fuel": {
    "fluid": "forge:ethanol"
  },
  "fePerMb": 975
}

**Comment by bdew** [comment]
fuel recipes currently don't work with tags, you need to give them the actual fluid id from a specific mod

**Comment by bdew** [comment]
I've checked, with latest versions something like this should work for tags

```
{
  "type": "advgenerators:liquid_fuel",
  "fuel": {
    "fluidTag": "forge:bioethanol"
  },
  "fePerMb": 100000
}
```

Added: Also your path is wrong, it should be e.g. datapacks\yourpackname\data\advgenerators\recipes\fuel\bioethanol.json
