### ISSUE TITLE
adding bcfuels to 1.12.2 ag

### ISSUE THREAD

**Issue by redfoxrommy** [bdew-minecraft/generators#207]
İ want to ad bc fuels to ag . i create a .crt file where should i put this file ?

fileneme bcfuels.crt
texts in it 

recipes {turbine-fuel: fuelLight 90 MJ/mB}
recipes {turbine-fuel: fuelDense 360 MJ/mB}
recipes {turbine-fuel: fuelMixedHeavy 96 MJ/mB}
recipes {turbine-fuel: fuelMixedLight 30 MJ/mB}
recipes {turbine-fuel: fuelGaseous 15 MJ/mB}

**Comment by bdew** [comment]
read this https://bdew.net/generators/configuration/
also it should be .cfg not .crt
