### ISSUE TITLE
Sensor Module GUI bug

### ISSUE THREAD

**Issue by Zuxelus** [bdew-minecraft/generators#210]
Advanced Generators 1.4.0.2 (MC 1.19.2)
In sensor module configuration GUI when click on modes it shows mode for a moment and then changes to Disabled.
When reopen GUI it shows correct mode.

**Comment by bdew** [comment]
Should be fixed in
* [BDLib 1.24.1.4 (MC 1.19.2)](https://www.curseforge.com/minecraft/mc-mods/bdlib/files/3963828)
* [Advanced Generators 1.4.0.3 (MC 1.19.2)](https://www.curseforge.com/minecraft/mc-mods/advanced-generators/files/3963836)
