### ISSUE TITLE
[1.19.2 Request] - Support for IC2 Classic

### ISSUE THREAD

**Issue by ToxinZangoose** [bdew-minecraft/generators#211]
Hello, love this mod for its convenience and accessibility.
Since IC2:C has been ported to 1.19.2, I was hoping that the support for EU would be enabled for the generators.

I'd love to see some way to hook up a transformer to the generator if the packets are too large for the cable or the machine.

Thank you for this incredible mod, I plan to use it as my main source of power. <3

**Comment by bdew** [comment]
No promises, but i'll look at it at some point.

**Comment by bdew** [comment]
Added with version [1.4.0.5](https://www.curseforge.com/minecraft/mc-mods/advanced-generators/files/4104739)

You have 5 tiers of output modules that you can add to generators (LV/MV/HV/EV/IV) and they will produce the appropriate power packets for IC2 cables/machines of that tier.
