### ISSUE TITLE
The mod is "ignored" by minecraft when running on 1.19 (the corresponding version)

### ISSUE THREAD

**Issue by xelanexxx** [bdew-minecraft/generators#212]
The mod is added, everything is as it should be, but it is ignored at startup, the error does not come out

**Comment by bdew** [comment]
Post full logs

**Comment by xelanexxx** [comment]
> Post full logs
there is nothing there at all. It's like the mod isn't installed.

**Comment by bdew** [comment]
There are always logs, if you can't provide them I have nothing I can do other than say "it works for me 🤷"
