### ISSUE TITLE
No bronze or enderium recipe

### ISSUE THREAD

**Issue by ArcusMG** [bdew-minecraft/generators#213]
Forge version: 43.1.58
Advanced Generators: 1.4.0.5-MC1.19.2
BdLib: 1.25.0.5-mc1.19.2
Scalable Cat's Force: 2.13.10-build-10-with-library
JEI (happens with or without JEI): 1.19.2-forge-11.4.0.286

Apologies if I made this bug report in error. I don't seem to have a recipe for bronze or enderium. When attempting to look up the recipe for advanced or composite turbine rotor in JEI, I get an error in the tooltip saying "Empty Tag forge:ingots/bronze" and "Empty Tag forge:ingots/enderium" respectively. 

I didn't see in the required mods, that I needed thermal expansion or foundation but I can add that if needed.
 
advanced turbine recipe: <img width="2048" alt="Screenshot 2022-11-28 at 2 47 56 PM" src="https://user-images.githubusercontent.com/20156689/204397592-37b216eb-d37e-4c99-a7ee-0b6122faaeb4.png">

composite turbine recipe: <img width="2048" alt="Screenshot 2022-11-28 at 2 48 08 PM" src="https://user-images.githubusercontent.com/20156689/204397669-707efb67-9280-493b-86cb-6c27988bf083.png">

**Comment by bdew** [comment]
There aren't any mods that are specifically required but you need *something* that provides those materials, Advanced Generators doesn't come with them by iteself.

Bronze there's like a billion mods that add it... my Factorium mod is one. It also has steel which can be used for turbines as well.

Thermal has a 1.19.2 version come out a few days ago, i haven't tested it yet but it should probably work for enderium.

There's also recipes for IC2 Classic if you have it installed in the latest version.
