### ISSUE TITLE
Cannot add new fuels

### ISSUE THREAD

**Issue by DigiF1sh** [bdew-minecraft/generators#214]
I'm running version advgenerators-1.4.0.5-mc1.19.2. 

The method described in the website to add new fuels doesn't appear to be working.

I created a .cfg file placed it in Config/AdvancedGenerators/ and wrote in the config file:

turbine-fuel: immersiveengineering:creosote 20 MJ/mB

and the fuel in question does not get added as a fuel.

**Comment by bdew** [comment]
That config is for the old system that is no longer used.

In current minecraft versions fuels are registered through data packs, e.g. https://github.com/bdew-minecraft/generators/blob/mc1.19.2/src/main/resources/data/advgenerators/recipes/fuel/mekanism_hydrogen.json
