### ISSUE TITLE
Sever Errors

### ISSUE THREAD

**Issue by Tomboru** [bdew-minecraft/generators#216]
Version: 1.19.2
Mod-Version: 1.4.0.5
Mode: Multiplayer

Description:
I started a server with the mod Advanced Generators, but I get several error messages in the console. I suspect that the errors are related to the fact that I do not have IC2 or Mekanism installed. I looked at the code of the mod and found that there is a check if these mods are present (isAvailable). The check returns False, but apparently the method registerMachines() is still called. This error is not urgent, but I wanted to report it.

The Errors:
https://pastebin.com/q1gJBpjG

Search for "Couldn't parse loot table"

**Comment by bdew** [comment]
You can ignore those, it's just minecraft complaining that the blocks aren't there when loading loot tables. It shouldn't affect anything other than some minor log spam.
