### ISSUE TITLE
Placed an Adv. Gen. Block and crashed

### ISSUE THREAD

**Issue by KillerInc** [bdew-minecraft/generators#23]
Im running 
bdlib-mc1710-1.6.1.39
generators-mc1710-0.9.7.35
and I'm required by Player to inform you I have
fastcraft-1.19 -> http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820

LOGs:
1st when I place the block.
http://pastebin.com/RPurERF0
2nd when i trying to log back in.
http://pastebin.com/9WX32Wxt

Edit: just confirmed that all is well on single player Its just not happy on the server

**Comment by Viper-7** [comment]
https://github.com/bdew/generators/blob/mc-1.7.10/src/net/bdew/generators/modules/rfOutput/BlockRfOutput.scala

First stab, Seems to register icons on the client only, then reference them from client and server?

**Comment by bdew** [comment]
It's an error in my code. Fix incoming. 

Icons and related stuff should never be registered or accessed on a server.

**Comment by bdew** [comment]
Try this versions (you need to update both):

http://jenkins.bdew.net/job/bdlib-1.7.10/40/artifact/build/libs/bdlib-mc1710-1.6.2.40.jar
http://jenkins.bdew.net/job/generators-1.7.10/36/artifact/build/libs/generators-mc1710-0.9.8.36.jar

**Comment by KillerInc** [comment]
been using it on my private sever since you updated no issues to report thanks for the quick update :)
