### ISSUE TITLE
Steam turbines have a hardcoded fluid input limit?

### ISSUE THREAD

**Issue by slawr34** [bdew-minecraft/generators#24]
As usual, not sure if bug:

I can only input a maximum of 250mb/t of steam into my turbine, regardless of how many fluid inputs/pipe connections I have.

**Comment by bdew** [comment]
There shouldn't be any limit. It will use up to 40 mb/t per turbine from the internal buffer, but if there's space in the buffer it should accept everything you pipe to it...

What's your exact setup?

**Comment by slawr34** [comment]
I have 9 turbines, which should equate to a max consumption of 360mb/t. On the turbine GUI it says the consumption is only 250mb/t - so I'm sure it's something to do with the actual input of fluid.

I have a RC steam boiler creating steam, which is getting pulled out with a Mekanism ultimate pipe (6400mb/t) which is placed in an iron tank. The steam is then pulled out of the iron tank with another line of ultimate pipe which is connected to the turbine. I think it might be the pipes themselves, but I don't have the materials to switch to EnderIO conduits yet.

Edit - checked, EnderIO conduits wouldn't be viable any way. The intermediate type has an extraction rate of 100mb/t, and the best only 200mb/t - which means I'd need multiple connections on the tank side which I can't really work.

**Comment by bdew** [comment]
Look at where the steam is building up (boiler, tank, pipes or turbine input buffer) - that's probably where the bottleneck is.

If you want you can also install [pressure pipes](http://bdew.net/pressure/) which will solve all your fluid throughput problems forever :P

**Comment by slawr34** [comment]
The bottleneck is definitely at the tank - it fills up faster than it drains and the input buffer of the turbine is stuck a 0.

I think I might do that, the thought of all the steam I'm wasting is making me angsty.

**Comment by bdew** [comment]
Yeah. I'm closing this as it doesn't appear to be a problem with my mod.
