### ISSUE TITLE
Obsidian NBT

### ISSUE THREAD

**Issue by Staegrin** [bdew-minecraft/generators#25]
Sorry to bother you again.

Just noticed after using the heat exchanger that the obsidian that gets produced has an NBT value that doesn't match normal obsidian.
![2015-02-16_18 44 27](https://cloud.githubusercontent.com/assets/8494635/6216622/25026da4-b60c-11e4-8e8f-fefc8a757ceb.png)
49:32767 instead of 49:0

This value means it can't be processed by machines like pulverizers or SAG mills. Also most recipes won't work with this version of obsidian.

Breaking the obsidian with a block breaker resets the NBT. Mining with a pickaxe doesn't.

Somehow dropping 63 with the wrong NBT, and picking them up when you already have one with 49:0 in your inventory will complete the stack and turn 63 of the obsidian with the wrong NBT into 49:0

**Comment by bdew** [comment]
Derp, will fix. 

BTW this is damage value (a.k.a metadata), it's not related to NBT. Placing and mining that obsidian back should reset it back to 0 unless some other mod is interfering with that.
