### ISSUE TITLE
Unable to pump Steam INTO Syngas producer

### ISSUE THREAD

**Issue by GotchaGimmeThanks** [bdew-minecraft/generators#27]
I know it can make it's own steam, but I was hoping I could pump some in from an external source, that would be excellent.

It would also be excellent if the Syngas producer could accept Sugar Charcoal as a source of carbon.

Great mod, thanks.

**Comment by bdew** [comment]
I'll look into adding this to the next version

**Comment by GotchaGimmeThanks** [comment]
Much obliged.

**Comment by bdew** [comment]
Fixed in af6375196004a3c94508bbdca38653e677037db2

**Comment by bdew** [comment]
oops forgot about sugar charcoal :P

**Comment by bdew** [comment]
Added fuels in 4cf5e6ffb1aae5eceae2e5be66b398fc9b14983b

**Comment by GotchaGimmeThanks** [comment]
Enjoying it, thank you.
