### ISSUE TITLE
World corruption and crash with Heat Exchanger

### ISSUE THREAD

**Issue by firespark81** [bdew-minecraft/generators#28]
Game crashes when I put an item output block onto the Heat Exchanger. If you reload the game reloads but then I thought it was just a normal crash so I attached ender io item conduit to it to export to a chest and it corrupted the world and would not reload. This is a potentially very bad bug. Here is the paste bin link to the crash report. Hope it helps http://pastebin.com/PE5VKZK5

**Comment by bdew** [comment]
Try this version: http://bdew.net/download/generators-mc1710-0.9.11.hotfix1.jar

I don't think there's any permanent damage to your world, this should fix the bug and allow it to work correctly.

**Comment by bdew** [comment]
Due to no response I'm assuming that this is fixed and closing the issue. If the problem still exists please comment here or open a new issue.
