### ISSUE TITLE
Add large scale fermentation/distillation

### ISSUE THREAD

**Issue by GotchaGimmeThanks** [bdew-minecraft/generators#30]
Loving advanced generators (and just recently added pressure pipes and gendustry, also awesome). 

Great if advanced generators also had a method for processing all my saplings and apples, maybe some kind of super fermenter, maybe something else. Any plans along these lines :)?

Frankly the distilling at large scale is even more a pain than the production of biomass.

**Comment by bdew** [comment]
I have something like that planned  in the future, but there are other things i want to finish first. Probably will be post-1.0

**Comment by Mementh** [comment]
I would suggest if possabile to have it output for other mods IE foresty so things are compatable?

**Comment by bdew** [comment]
The process (when implemented) will be not directly related to forestry but i'll try to make the fuel produced compatible with as much stuff as i can.

There's a very good chance that this won't be implemented before a transition to MC 1.8 (or maybe 1.9?) - so i'll figure out the actual details depending on how other other mods look at that point.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
