### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ivardensphere** [bdew-minecraft/generators#33]
This may sound strange but I am getting a crash with advanced generators when using metallurgy and Thermal Expansion..

Someone had reported this crash before but no one could figure out the cause. 
I tore apart my pack one mod at a time (over 200+ mods) and the cause is created every time when I put in advanced generators. Take it out, no longer the issue.

I posted this on the metallurgy github as well:
https://github.com/TeamMetallurgy/Metallurgy4/issues/65

The log is:
http://pastebin.com/Vmp2HjPM

Hoping to shed light on whatever this cause is.

**Comment by bdew** [comment]
Did you try reporting it to the CoFH team? The immediate crash happens in their code.

I'm have no idea how this has anything to do with my mods as none of them are even mentioned in the crash.

**Comment by ivardensphere** [comment]
Yeah it was posted via:
https://github.com/CoFH/Feedback/issues/158#issuecomment-75463001

TeamMetallurgy is claiming it's not them. COFH is saying not them either.

Only reason I posted here was when advanced generators is removed, the crash does not take place :/

**Comment by bdew** [comment]
Well that is really odd. The only thing i do with TE is register a single induction smelter recipe, and i do that using the normal IMC method. And i don't do anything with metallurgy at all.

I'll try grabbing metallurgy and attempt to reproduce it when i have the time to poke it with a debugger, maybe i can figure what's going on.

**Comment by ivardensphere** [comment]
If you need any more information let me know! Always glad to help out modders.

**Comment by bdew** [comment]
Sorry for the long delay... i've tried reproducing it with current versions and it's not crashing.

Can you check if it's still crashing? if it does give me the exact versions of all mods involved.

**Comment by bdew** [comment]
Since i've received no response i'll assume it's working now. If you still have any issues comment here or open a new issue.
