### ISSUE TITLE
Tiered turbines do not actually use their production values (in the gas turbine multiblock)

### ISSUE THREAD

**Issue by smbarbour** [bdew-minecraft/generators#34]
I know the new turbines are not officially released yet, but from the current jenkins build, the gas turbine controller only counts the number of turbines and multiplies that by the default value without regard for the material of the turbine.

https://github.com/bdew/generators/blob/mc-1.7.10/src/net/bdew/generators/controllers/turbine/TileTurbineController.scala#L86-L87

It appears that the steam turbine controller DOES take into account the material of the turbine however

**Comment by bdew** [comment]
Yeah it's not implemented yet in gas turbine controller

**Comment by Skar78** [comment]
The Unabridged pack from Bboldt really brings out the best in Adv, Generators.

The tiered Turbine Update is probably on top of the list for every unabridged player. I just build steam generators just to use those, so great.
 Will be even more great once the syngas is working.

Totally hope there are no show stoppers for this.
