### ISSUE TITLE
[Suggestion] IC BioGas in the Gas Turbine

### ISSUE THREAD

**Issue by nintendow131** [bdew-minecraft/generators#35]
It would be cool, if you could burn IC2 Biogas in a multiblock Gas turbine, because you have to
build a lot of semilfuid gens.
One bucket of Biogas burns for 16 EU/t at a usage of 0,5 mb per tick for a total of 3200 EU/t
One bucket should burn for 32EU/t at 1mb/t with a Gas Turbine.
@ higher efficiencies i think it should use a bit less mb/t.

**Comment by bdew** [comment]
> One bucket of Biogas burns for 16 EU/t at a usage of 0,5 mb per tick for a total of 3200 EU/t

Are you missing a zero here?

> One bucket should burn for 32EU/t at 1mb/t with a Gas Turbine.

Turbines don't work like that. The throughput is determined by number and type of turbines.

I'm putting the base value at 128 RF/mB which ends up at about 35.5 kEU per bucket with all the bonuses.
