### ISSUE TITLE
Suggestion: Charcoal Production

### ISSUE THREAD

**Issue by Skar78** [bdew-minecraft/generators#36]
The Heat Exchanger neatly solves steam production with lava and water for steam turbines, however the syngas producer requires other mods/outside sources for solid fuel.

For bigger systems even the charcoal production of a maxed elite factory smelter from mekanism might not be enough. (I currently run a elite factory AND an oct. alloy smelter.)

I was wondering if a flexible extensible charcoal producing multiblock would make a worthwhile addition to the mod and want to flash out the idea a little bit..

For inspiration I refer to the wikipedia article about charcoal production:
 https://en.wikipedia.org/wiki/Charcoal#Production_methods

So imagine a "condenser" multiblock structure that uses either RF or solid fuel for dehydrating wood into charcoal and the production capacity can be extended similar to the other multiblock structures.

Maybe a clever synergy with the heat exchanger (maybe the condenser outputs additionally water from dehydration of the wood and the heat exchanger can also burn solid fuel for heat) would make it rewarding to have both power generations (steam + gas) together with heat exchanger and condenser in a setup. without breaking the individual utility of the current system.

I regard adv. as a great "quality of life" mod and feel this would further add to that.

Of course this might go in a totally different direction than your vision for your mod, i respect that, still writing this here should not hurt.

Love the mods and hope you keep up the good work.

**Comment by bdew** [comment]
You can put wood logs directly into the syngas producer and they have the same value as charcoal.

**Comment by Skar78** [comment]
Oh. Sorry about that.

A "charcoal" equals "log" + "energy to burn it" so should a log alone not provide less energy?

**Comment by bdew** [comment]
Well technically "log" + "energy" = "charcoal" + "water and other organic crap removed from the log by said energy"... except we ignore the last part in Minecraft.

Here steam (H2O) reacts with the carbon (C) to produce syngas (CO and H). Considering that you don't increase the amount of carbon in a log by turning it into charcoal - i don't see why they should have a different value.

Also you can carry 2304 m³ of rock in your pockets. Don't try to think too hard about Minecraft physics :P
