### ISSUE TITLE
Gasses/Fluids from other mods?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [bdew-minecraft/generators#37]
What about adding gasses/fluids from 

http://minecraft.curseforge.com/mc-mods/224613-engineers-toolbox
http://minecraft.curseforge.com/mc-mods/68023-mariculture
http://minecraft.curseforge.com/mc-mods/73373-minechem

?

**Comment by bdew** [comment]
Minechem - i need to sit and figure out what makes sense to use as fuel or carbon source and how to balance it all (i imagine it will be all kinds of a headache).

The other 2 - i'm not really familiar with those mods at all. If you  can provide a list of fluids/materials in them that would make sense to use i could include that.

**Comment by Unrepentant-Atheist** [comment]
Mariculture: http://i.imgur.com/pkXYWq1.png
Engineer's Toolbox: http://i.imgur.com/Uo4jupC.png

**Comment by bdew** [comment]
Engineer's Toolbox hydrogen and natural gas seem to generate 30 RF/mB in their generator module so i'll use that value.

Mariculture has natural gas as well but i have no idea what value to give it, i'll go with the same 30 RF/mB unless/untill someone complains :P

**Comment by bdew** [comment]
i've added carbon, hydrogen and a bunch of molecules from minechem as well.

If anybody wants to look through the numbers and tell me if they make any sense - comments are welcome, otherwise i'll close this issue in a bit.

**Comment by Unrepentant-Atheist** [comment]
I added these to my own config, do you think they make sense, number wise?

```
turbine-fuel: oil 40 MJ/mB
turbine-fuel: fuel 150 MJ/mB
turbine-fuel: creosote 45 MJ/mB
turbine-fuel: biomass 60 MJ/mB
turbine-fuel: hootch 50 MJ/mB
```

**Comment by bdew** [comment]
Fuel should work by default - it's value is getting imported from BuildCraft (unless there are other mods that provide fuel?)

Biomass, hootch, oil are precursor to other fuels (ethanol, rocket fuel/firewater, fuel) so i like having people refine them properly.

Creosote... not sure, it would make sense to have from a gameplay perspective but it doesn't sound realistic to run a turbine on it.

**Comment by Unrepentant-Atheist** [comment]
Right...Hootch though is alcohol already :P. Refining hootch into other alcohol just adds more energy value to it. So Hootch is fine, I think.

Oil per se...I dunno, it's unrefined, crude energy which can be used as fuel in a pinch, but is wasted if not properly refined.

Creosote as fuel is fine. Burning creosote to create steam to power a turbine. :P

So...what would you add for hootch, oil and creosote?

**Comment by bdew** [comment]
Hootch - 36
Oil - 15
Fuel - 150 (this is the value that gets imported from BC)
Biomass - 12.5
Creosote - 14.3 (based on RC boiler simulator)

**Comment by Unrepentant-Atheist** [comment]
Nice. Much obliged!
