### ISSUE TITLE
Feature request for Syngas Producer

### ISSUE THREAD

**Issue by cloakable** [bdew-minecraft/generators#38]
Railcraft coal coke blocks now have a burn time of 10x the value of one coal coke, but setting the carbon value to 32000 results in the syngas producer not accepting blocks.

Can you add a config setting for how much carbon/steam the mixing chamber can hold?

**Comment by bdew** [comment]
> InternalTankCapacity = 32000

This is the value that's used for the chamber. It should work with 32000 if the chamber is empty ...

**Comment by bdew** [comment]
There were 2 bugs causing it to not work, both now fixed. I've also increase the default value to 32000
