### ISSUE TITLE
[Feature Request] Redstone Control Module: On Pulse: Clear Internal Buffers

### ISSUE THREAD

**Issue by MyNameIsKodos** [bdew-minecraft/generators#41]
As the title states, being able to clear the buffers can help with remotely clearing any congestion in the machines without having to trod back down to the machine room or wherever you're keeping the turbines.

Also, the RF/EU generating blocks need the canConnectRedstone flag so enable on redstone can be used with P:R cables and the like

Edited out the edit because I'm an edit... err I mean idiot.

**Comment by bdew** [comment]
Added canConnectRedstone to a everything that made sense, tell me if i missed something.

For clearing - there are technical limitations to doing this with the current implementation of control modules, though i can see it being useful.

I'll leave this open until i get around to implementing it.

**Comment by MyNameIsKodos** [comment]
Redstone stuff looks good!  Sorry for being a pest about it, but for what it's worth, you're not the only one I've been pestering about canConnectRedstone lol

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
