### ISSUE TITLE
RF Output does not work with Energy Extraction Pipe

### ISSUE THREAD

**Issue by twothe** [bdew-minecraft/generators#42]
When using an Energy Extraction Pipe from Extra Utilities on a Flux Generator, the pipe will connect, but no energy will be transfered. A Transfer Node (Energy) does work, but this is undesirable, as the node prefers generators based on distance (which preferably is something like a solar generator).

For clarification:
![power](https://cloud.githubusercontent.com/assets/1131621/8647051/f30db26a-2954-11e5-9c28-0c68338099b0.jpg)

**Comment by bdew** [comment]
Looking at the screenshot it's not recognized as a valid output (there's a red output pointing to the node, but none to the pipe). Either that or you already have 6 other outputs.

I'll need to look into how it's implemented in ExU. RF can work with either push or pull mechanic, most things work with push (so generator pushes to pipe which pushes to machine) or support both, if it only supports pulling - it won't work.

**Comment by twothe** [comment]
The screenshot is just for clarification which items are used. The output does not work even if the items are correctly attached. In my case I had the extractor pipe at the place where the node is now.

**Comment by bdew** [comment]
It looks like extraction pipes won't work with my generators with how they are implemented. You can work around this by using some kind of buffer between the generator and the pipe (e.g. TE energy cell or EnderIO capacitor bank)

**Comment by twothe** [comment]
Neither is available in my mod-pack. I am currently trying a low-tech variant as by your own advice. ;)
