### ISSUE TITLE
Signal "On empty power capacitor " does not work

### ISSUE THREAD

**Issue by twothe** [bdew-minecraft/generators#43]
The sensor module does not output a signal if the power capacitor is empty. As far as I can tell this happens if only a fraction of power is left inside it. 

In addition power values below a certain threshold are unable to be requested by an attached power network, in which case the capacitor might have something like 2 RF left, but still won't count as empty.

For the later I'd suggest to add a selector like  "below 5%".

**Comment by twothe** [comment]
Thank you.

Out of curiosity: how do I use the "over 5%" detection as "below 5%"?

**Comment by bdew** [comment]
by putting any kind of a not gate on it :P

**Comment by twothe** [comment]
Good Guy Project Red to the rescue. ;)
