### ISSUE TITLE
Crash On Load Up After Updating To 0.9.16.96 (Tooltip)

### ISSUE THREAD

**Issue by RoloEdits** [bdew-minecraft/generators#44]
http://pastebin.com/7SUWC6bh

**Comment by bdew** [comment]
update bdlib to 1.9.1

**Comment by RoloEdits** [comment]
Thanks you very much.
the download for 1.91 wasn't available on curse when I downloaded the update for generators.
sorry for the trouble.

**Comment by bdew** [comment]
Yeah curse sometimes takes a while to approve the files. For the future you can always get the latest builds on [my jenkins](http://jenkins.bdew.net/)

**Comment by RoloEdits** [comment]
OK I will do that from now on :)
