### ISSUE TITLE
Not able to draw power from generator

### ISSUE THREAD

**Issue by sturmgewehr-44** [bdew-minecraft/generators#45]
After I figured out that only a fluid transfer node would provide liquid to the generator I was able to make power but now I can't use it I have tried every energy connection and direct machine connection but no output! I'm using 9.14.99 adv gens.  I have buildcraft, openblocks, tink const, ender IO,AE2 , and thermal expansion.  Some connections are recognized but will not transfer energy. Even to their own mod machines

**Comment by bdew** [comment]
Post a screenshot of your setup and your logs

**Comment by sturmgewehr-44** [comment]
Sorry think I figured it out,  my buildcraft was very out dated.  Seems to be working now thank you for responding quickly.
