### ISSUE TITLE
Turbine Modules not producing proper amount of RF

### ISSUE THREAD

**Issue by Skyler-Altol** [bdew-minecraft/generators#50]
Bit of a bug going on in my RR3 installation, (It's running 0.9.14), where the turbine tiers are still producing 100 RF/t per turbine. Irrelevant of what type of turbine I use... Was this fixed in the newer updates? I did not see this mentioned in the changelogs.

Cheers,
LC14199

**Comment by Skyler-Altol** [comment]
Further investigation shows that this only affects the Gas Turbine Controller multiblock, not the steam turbine controller multiblock.

**Comment by bdew** [comment]
Are you running a beta version of 0.9.14 by chance? 

The release one (0.9.14.89) should have it working for both gas and steam turbines.

Added: All builds after [.84](http://jenkins.bdew.net/job/generators-1.7.10/84/changes) should have it working.

**Comment by Skyler-Altol** [comment]
I'll take a look.

**Comment by Skyler-Altol** [comment]
Oh you're kidding me. The RR3 devs put 0.9.14.79 in the pack release version... total n00bs. I'll get onto them and make them do a hotfix, thanks for your help haha. Sorry if I sounded like a n00b xD
