### ISSUE TITLE
Unable to make Advanced Pressure Value in Induction Smelter

### ISSUE THREAD

**Issue by utoc** [bdew-minecraft/generators#51]
Hi!

One of my users has come across an issue today in AdvGens 0.9.17.102.  The induction smelter happily accepts the enderium ingots and pressure valve but never starts actually smelting them to make an advanced pressure valve.  The recipe shows up in NEI just fine, it just doesn't do the thing.  The EnderIO Alloy Smelter works just fine with 8 vibrant ingots and an advanced pressure value.

https://i.imgur.com/yKWTEPZ.png

I'm running CoFH 3.0.3-303, Thermal Foundation 1.2.0-102 and Thermal Expansion 4.0.3B1-218 with FML 1448

Where have I gone wrong?  What troubleshooting steps can I take?

**Comment by utoc** [comment]
We figured the issue out.  The basic smelter only holds 48k rf.  The recipe requires 50k rf and it won't craft it until it has all the rf in one go.  Could you consider changing the recipe to 48k as opposed to 50k?  Or not, whatever suits you :)

**Comment by bdew** [comment]
It's already fixed to be 48 in alpha builds and will be in next release - https://github.com/bdew/generators/commit/eb4c7fe2e63e65636ef50b3b2bfe74c37b0d0893
