### ISSUE TITLE
[Feature Request] OC / CC support

### ISSUE THREAD

**Issue by CrazyCodeUK** [bdew-minecraft/generators#53]
I would like to request support for OpenComputers / Computer Craft in a similar style to Pressure Pipes. With a Data Port for the generators. With simple interaction for reading fuel capacity, current fuel level, max generation (somthing like a simple array with max possible for each output type currently installed), current generation, energy stored, max energy storable ect.

Enjoying the mod, thanks :)

**Comment by bdew** [comment]
Already planned, once i get it fully working in PP i'll add it to this mod as well

**Comment by hron84** [comment]
Currently, it would be enough if you can implement Forge tank support (if you do not do it already) to be able to detect the amount of the stored fuel and normal RF interfaces to interact with internal RF storage.

**Comment by hron84** [comment]
@bdew is there any new info about this? In PP it seems like works like a charm. Fluid infos can be read/written.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
