### ISSUE TITLE
Add Mekanism pipe support to ItemPush

### ISSUE THREAD

**Issue by rstat1** [bdew-minecraft/generators#56]
I can't seem to export any of the obsidian generated by making steam in a heat exchanger. Is this possible or do I have to manually go and press the Clear Buffers every few minutes?

Unless I'm missing something....if I am, sorry.

**Comment by bdew** [comment]
Are you using an item output port ?

**Comment by rstat1** [comment]
That was one of the things I tried. I added an Item Output port, and connected a mekanism logistical transporter pipe between it and a chest. 

Nothing happened.

**Comment by bdew** [comment]
Try putting a chest directly next to it or connect it to either BC pipes, TE ducts or EIO conduits.

**Comment by rstat1** [comment]
The mod pack I'm playing (FTB Horizons Daybreaker) has none of those things. Putting a chest directly in front of the output port did work however.

So my next question would be, is the mekanism transport pipe supposed to work, or is it not supported?

**Comment by bdew** [comment]
Not supported for now. I'll look into adding it, leaving this issue open as a reminder :P
