### ISSUE TITLE
Supporting Galacticraft fuel/oil?

### ISSUE THREAD

**Issue by zhs2** [bdew-minecraft/generators#58]
Like Buildcraft fuel/oil, only exported to the configuration file instead of hidden within the code as "exported Combustion Engine fuels".

**Comment by bdew** [comment]
I'm completely unfamiliar with the mod so unless someone can give me a list of fuels, their IDs and energy values - i'll need to look through it first when i have the time.

**Comment by zhs2** [comment]
As far as I know, Galacticraft fuel/oil are meant to be compatible with Buildcraft fuel/oil uses, and are, in fact, completely interchangeable, so the fuel values are meant to be the same. The only thing I'm not sure of is whether Buildcraft oil is burnable as a fuel. (And if it is, I know it's meant to be a poor fuel in need of refining.) This mod is the only place I've run into where said oil/fuel aren't supported right off the bat if Buildcraft isn't installed. In any case, here are some dumped details:

ID,Name,Localized Name,Temperature,Luminosity,Density,Viscosity,Placeable,Block ID,Block Class
3,oil,fluid.oil,300,0,800,1500,true,GalacticraftCore:tile.crudeOilStill,micdoodle8.mods.galacticraft.core.blocks.BlockFluidGC
4,fuel,Fuel,300,0,400,900,true,GalacticraftCore:tile.fuel,micdoodle8.mods.galacticraft.core.blocks.BlockFluidGC

**Comment by bdew** [comment]
Fuel should work in next alpha build. Oil won't work in turbines, it needs to be refined into fuel first.
