### ISSUE TITLE
[Question] How to add custom assets files for custom materials?

### ISSUE THREAD

**Issue by OneEyeMaker** [bdew-minecraft/generators#59]
I'm trying to add custom materials for turbines (by overriding 'turbine-modules.cfg'). And all works fine.
But I have problems with adding localization and textures. Mod skips any .lang/.png files in {mc_dir}/config/AdvGenerators/ (and I have pink and black blocks without localization).
Please, explain, how to add custom turbine materials with adding localization and textures.
And add this information to the site (I can't find this information now for AdvGenerators - only for Gendustry).

P. S. Thank you very much for your work! Your mods are awesome!
P. P. S. Sorry for my English, I'm from Russia.

**Comment by bdew** [comment]
Currently loading assets from the config folder is not supported. This is something that i would like to add in the future but there are issues with that.

For now you can use one of those options
- Put them in the mod jar (not recommended - you will need to keep it updated when you update the mod)
- Put them in a separate jar in the mods folder, following the structure of the mod jar
- Put them in a resource pack

**Comment by OneEyeMaker** [comment]
Thank you very much!
