### ISSUE TITLE
Include GT power generator

### ISSUE THREAD

**Issue by BakermanLP** [bdew-minecraft/generators#6]
This is a improvment suggestion.
I saw, that the mod powerconverters recently added support for Gregtech power. It would be nice to see a GT generator (like the IC2 generators) in your mod
Thanks a lot for this mod
Michael

**Comment by bdew** [comment]
I wasn't even aware GT has it's own power system nowadays, i'll look into how feasible adding it would be when i can.

**Comment by BakermanLP** [comment]
I think a look at the PowerConverter Sources could be helpfull, but I can't write a single line in java:
Here are the source files:
https://github.com/portablejim/PowerConverters
... and this is the commit for GT Power:
https://github.com/portablejim/PowerConverters/commit/5c46efed2a8bc1e5b037faa282ab2075eb1617f0

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
