### ISSUE TITLE
Generators not accepting fuel

### ISSUE THREAD

**Issue by hugetacoHTML** [bdew-minecraft/generators#60]
Hi, I am on DNS Techpack version 7712, using advanced generators version 0.9.16.99-mc1.7.10. Fuel types in NEI say that they will generate a certain amount in the turbine generator, but I cannot get the generator to fill up with the fuels. I tried connecting BC pipes, mekanism mechanical pipes, and thermal expansion portable tanks to the fluid input valve on both steam turbine generators and gas turbine generators, but I still cannot get the actual fuel to get into the generator. I believe this is because it isn't accepting it, but as I said I looked around in the .jar file and found the config file, and all the fuel types were there. What am I doing wrong?

**Comment by bdew** [comment]
Can you upload a screenshot of your setup?

**Comment by hugetacoHTML** [comment]
Hi, my friend and I actually found the fix to the problem. Apparently the gas generators only accept Buildcraft Fuel (Gasoline). Even if this is not supposed to happen, this was fine by us as we had tons of oil to use. Anyways, great mod, looking towards future builds!
