### ISSUE TITLE
Mekanism Biofuel not accepted in Syngas Producer

### ISSUE THREAD

**Issue by leglerm** [bdew-minecraft/generators#61]
Well as the Title says it is not working as a carbon source.
Setup is fine as we tried wood/coal and it is working fine.

generators-0.9.18.113-mc1.7.10
Mekanism-1.7.10-8.1.7.252

**Comment by bdew** [comment]
No idea why that stopped working, but switching the default configs to use the item directly instead of oredict seems to fixed. Will be in next alpha build.
