### ISSUE TITLE
Heat exchanger incorrect worked with last IC2_exp

### ISSUE THREAD

**Issue by Neuromantix** [bdew-minecraft/generators#62]
Heat exchanger incorrect worked with last IC2_exp - steam and coolant outed in one pipe(s) together, separatle out don't work

**Comment by bdew** [comment]
You can change what fluid goes where in the output configuration screen

![2015-10-26_16 27 13](https://cloud.githubusercontent.com/assets/96327/10731905/3c685f8e-7c00-11e5-8bdd-d9f3f832fafb.png)
