### ISSUE TITLE
Suggestion: Output Priority

### ISSUE THREAD

**Issue by cjo9900** [bdew-minecraft/generators#63]
Seeing as 6 power outputs can be added to a turbine generator
It would be nice to set the priority order of where the power is sent when generation is not enough for consumption.
Currently playing Galactic Science modpack and would like my oxygen generation, and farms to always have power while mob spawner's to be starved if demand is too great.

Unless this is already done by the order of the connections in the output list.
(which I don't see happening)

**Comment by Mementh** [comment]
agreed.. would prefer to see a priority..

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
