### ISSUE TITLE
Gas Turbine Consumption Bug

### ISSUE THREAD

**Issue by StaticV** [bdew-minecraft/generators#64]
ethylene seems to be consumed at a much lower rate then it should be.  from your wiki it should be generating 600 RF/mb but it appears to be generating about 10 times that much.

![image](https://cloud.githubusercontent.com/assets/5557846/10948597/66188306-82fc-11e5-830f-44a370670e9e.png)

I'm using GENERATORS-0.9.17.102-MC1.7.10 from RR3

**Comment by bdew** [comment]
Is that from mekanism? The numbers look right to me (yes it's very powerfull, that's how it's in mekanism itself) so i think this is an error in the documentation.

At any rate the list of fuels is very incomplete and i should update it :P

You can see the default configs for all the fuels here for now - https://github.com/bdew/generators/blob/mc-1.7.10/resources/assets/advgenerators/config/turbine.cfg#L128 (note that the values are in MJ, so to get RF/mB they need to be multiplied by 10)

**Comment by StaticV** [comment]
Yes its from mekanism,

> turbine-fuel: ethene 600 MJ/mB

Yep its 6000 RF/t, I double checked the rest against the wiki, they're all the same.

I was just confused why syngas made from mekanism bio fuel burns so quickly in the gas turbine but ethene made from the same amount of bio fuel takes forever, and i guess the answer is because its comparable rate to the mekanism gas-burning generator which itself is OP

I reformatted your config file data to your wiki format if you want to copy paste it in, it would be more complete but i have no idea what mod these come from lol

Natural Gas – 30 RF/mB
Hydrogen (GasCraft) – 30 RF/mB
Natural Gas (GasCraft) – 30 RF/mB

Element H -  4 RF/mB
Propane - 268 RF/mB
Butane - 272 RF/mB
Isoprene - 276 RF/mB
Toluene - 284 RF/mB
Ethanol - 136 RF/mB
Aalc - 140 RF/mB
MeOH - 68 RF/mB
Methyl - 100 RF/mB
Methylene - 68 RF/mB
Methacrylate - 180 RF/mB

Diesel - 700 RF/mB
Kerosene - 1100 RF/mB
LPG - 1800 RF/mB

Light Oil - 2000 RF/mB
Heavy Oil - 1500 RF/mB
Natural Gas - 3000 RF/mB
