### ISSUE TITLE
Extream Voltage Emiter

### ISSUE THREAD

**Issue by darth62969** [bdew-minecraft/generators#66]
So we have MV HV and LV emitters so can we get an EV emitter that emits up to 8192EU/t for IC2? 

(now if only we had a way to store those packets...)

**Comment by bdew** [comment]
You can actually run EV output directly into a MFSU nowadays with the non-exploding energy system.

That's one of the reasons i wasn't sure about adding it. Tho i guess by the time you have enough turbines (and steam/fuel to feed them) to bother with EV it's not really much of a balance issue...

**Comment by darth62969** [comment]
i was wondering why my machines weren't exploding. did they seriously stop
making machines explode when you hook them up to higher voltages?

(: Jonathan :)

**Comment by bdew** [comment]
Yep, it was removed when they started rewriting the energy system.

It was supposed to return once the system is more stable, but that was a long time ago, so not really sure what's the current status of that "feature".
