### ISSUE TITLE
Cant use Redstone Control Module with Heat Exchanger (0.9.19.120)

### ISSUE THREAD

**Issue by GarradStacey** [bdew-minecraft/generators#68]
Redstone Control Module is not considered attached to a valid machine when used as part of a Heat Exchanger. This conflicts with the statement on the wiki saying each can contain up to 10 control modules. Of note is that the tooltip that explains what it can be used with does not list Heat Exchanger - whereas it does for the other three machines (steam turbine, gas turbine, syngas producer). I was hoping to setup a system where I can disable heat exchanging once the hot liquid output tank is full.

**Comment by bdew** [comment]
Are you using any kind of custom configs?

It works for me and i honestly see no reason why it could break unless explicitly disabled in the configs.

![2016-01-05_17 13 59](https://cloud.githubusercontent.com/assets/96327/12118593/04171302-b3d0-11e5-8b32-6f91c1dbb956.png)
![2016-01-05_17 14 09](https://cloud.githubusercontent.com/assets/96327/12118592/0411f98a-b3d0-11e5-8b86-aff5b4778178.png)
