### ISSUE TITLE
mekanism ethylene rf/mb wrong?

### ISSUE THREAD

**Issue by Mementh** [bdew-minecraft/generators#69]
I am testing this on a server where all the defaults are used and 1000mb from a gas tank of ethylene is producing without fuel air/gas mix
6,599,950 RF which is  6599.95rf/mb and the wiki says it should make 600 rf/mb whoppsie!

syngas with alot of testing got for 1000mb 
1,100,000 rf or 1100 rf/mb ( this is also higher then expected)

I know https://github.com/bdew/generators/issues/64 brought something like this up but i don't think it was addressed.
I would expect to get out 600,000 RF not 10x the ammount

we are using version 0.9.18.113 

could you explain how i am misunderstanding or if its wrong?

**Comment by bdew** [comment]
Yeah i haven't actually updated the site after the discussion in #64, sorry.

It should be up to date now. I've also clarified (i hope) that the value is modified by the efficiency multiplier (110% by default, up to 185% with upgrades).

https://bdew.net/generators/turbine-generator/

If there's still something unclear or incorrect - please let me know.

**Comment by Mementh** [comment]
_huggles_ I was thinking it was majorly broken!!! glad it was intended.. but it does cut out the syngas machines as a normal way of fueling outside the mod :/ but thats just how the cookie is made
