### ISSUE TITLE
[Suggestion] Provide example config for fuel customization

### ISSUE THREAD

**Issue by hron84** [bdew-minecraft/generators#71]
I read in the config you provide in the JAR file there is a way to add more fuels to burn. It would be good if the mod could generate a config file filled with examples in the config folder instead of hiding it in a JAR file because it's quite hard to notice a hidden config options. And even if I read the config I still not have an idea how can I add more fuels (for example ImmersiveEngineering's Biodiesel).

**Comment by novasolarius** [comment]
https://github.com/bdew/generators/tree/mc-1.7.10/resources/assets/advgenerators/config
That's your examples.

**Comment by bdew** [comment]
Sorry about not responding sooner, i somehow missed this issue.

You can make a file in <minecraft>/config/AdvancedGenerators named <whatever>.config and put in it something like:

```
recipes {
         turbine-fuel: <fluidname> <value> MJ/mB 
 }
```

You can get a list of fluids from using /dumpregistry command (it's part of BDLib)

Also there's documentation of the format [here](http://bdew.net/bacon/) and [here](https://bdew.net/generators/configuration/)

**Comment by hron84** [comment]
@bdew Can you link the config format [here](https://bdew.net/generators/turbine-generator/) for easier discovery?
