### ISSUE TITLE
Could steam turbine have a fluid output?

### ISSUE THREAD

**Issue by SigurdCole** [bdew-minecraft/generators#73]
One of the major advantages of Big Reactors is that you can have a closed-loop (or nearly) water supply, instead of having to supply substantial amounts of water constantly. From the wiki, it looks like the steam turbine generators don't have that capability. Could that be added? It would be a great enhancement.

Thank you! Your mods are awesome!

**Comment by Paxination** [comment]
You do realize you just posted an issue for the mod AE2 Stuff which is an Applied Energistics 2 add-on?  And your asking about adding a feature into a mod that bdew doesnt own?  He doesnt code for Big Reactors.

**Comment by bdew** [comment]
This is actually for Advanced Generators :P

I might add it in the future, currently burried neck deep in 1.8.9 porting of stuff.

**Comment by Terpo** [comment]
Are there any news on this? I was trying to combine a fluid reactor of ic2 + heat exchanger + steam turbine. The coolant control is fine but the huge water consumtion for water->steam is overkill ^^
I am speaking of the current 1.10.2 version of Adv. Generators.

**Comment by TedKnudsen** [comment]
Last time I bugged him about this it was still in the Soon(tm) stage :p 

But, yes, configurable outputs would be massively amazing.

**Comment by pyure** [comment]
Last time I bugged him about this it was still in the Soon(tm) stage ;)

But, yes, configurable outputs would be massively amazing.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.

**Comment by pyure** [comment]
@bdew , I'm still a heavy user of this mod.  I'd been meaning to ping you again on this but I hate prodding.  

If you're willing it to return it to the Soon(tm) list:
* Steam Generator multiblock should permit an Output fluid hatch
* Output hatch should produce water based on the amount of steam consumed
* Standard rate is (I believe) 1 mb water for every **160** mb steam produced (correction)
* ** BONUS ** make the rate configurable
* ** BONUS ** make the fluidstack type configurable

Right now I get by by leveraging (lots of) various infinite water mechanics to drown the multiblock, but a Adv. Gen. solution is preferable.

**Comment by Terpo** [comment]
Confirm, feature request is still wanted on our side.

**Comment by bdew** [comment]
Sorry i'm not going to be accepting feature requests in the issue tracker, as their inflow far outpaces my ability to implement them (which is one of the reasons why that cleanup was needed).

I'm going to figure out a better platform to manage feature requests soon (tm).
