### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by GotchaGimmeThanks** [bdew-minecraft/generators#74]
I was looking at your customization explanations:
https://bdew.net/generators/configuration/

If I'm using method #1, then what is the correct text for the file? I see there's a guide for what to write, but what goes around it? I think it'd be good to see an actually example of one properly done.

Sorry to ask for a spoon feeding, but while I'm trying to get a sample of correctly formatted text I may as well mention the actual things I want to change:
1. I'm hoping to include RotaryCraft ethanol
2. Enable up to 1,000 turbines per generator
3. Enable up to 500 Mixing Chambers/Syngas Producer

Thanks Bdew!

**Comment by bdew** [comment]
Look a tthe [default configs](https://github.com/bdew/generators/tree/mc-1.7.10/resources/assets/advgenerators/config) for examples, they use the same format.

For what you want it'd be something like:

```
recipes {
         turbine-fuel: <fluidname> <value> MJ/mB 
}

cfg Machines {
    cfg TurbineController {
        cfg Modules {
            Turbine = 1000
        }
    }

    cfg SteamTurbineController {
        cfg Modules {
            Turbine = 1000
        }
    }
    cfg SyngasController {
        cfg Modules {
            MixingChamber = 500
        }
    }
}
```

**Comment by GotchaGimmeThanks** [comment]
Thanks Bdew!

Increased number of turbines is working, and I love it.

Can't get the RoC Ethanol to work though. Reika mentioned something about that liquid being handled a bit differently than most liquids. Interestingly it has no item listing for the actual fluid in NEI, Still, as with some other fluids, which lack actual source blocks, it can go through ducts and tanks.

What I typed for the .cfg file:

recipes {
         turbine-fuel: Ethanol 800 MJ/mB 
}

cfg Machines {
    cfg TurbineController {
        cfg Modules {
            Turbine = 1000
        }
    }

```
cfg SteamTurbineController {
    cfg Modules {
        Turbine = 1000
    }
}
cfg SyngasController {
    cfg Modules {
        MixingChamber = 500
    }
}
```

}

**Comment by bdew** [comment]
Try putting

```
turbine-fuel: "rc ethanol" 800 MJ/mB
```

**Comment by GotchaGimmeThanks** [comment]
Success!
