### ISSUE TITLE
Crashing starting modpack with 1.8.9...

### ISSUE THREAD

**Issue by Sasikaa** [bdew-minecraft/generators#76]
Put the new 1.8.9 generators mod, and bdlib. starting my modpack, and crash when loading.
Crashlog:

http://pastebin.com/m2dEUuPe

**Comment by MrGraphic** [comment]
Probably accidential PressurePipes dependency. You will need to add this or wait for a fix.

**Comment by Sasikaa** [comment]
Thanks!

**Comment by LlubNek** [comment]
Here's another crash report:
http://pastebin.com/mdiCq9dZ

**Comment by bdew** [comment]
Should be fixed in next build.

The soft-dependency used to work in 1.7.10 in the exact same way, but looks like something has changed in how forge/mojang load classes and it broke something, this is super annoying.
