### ISSUE TITLE
better usage display ideas for gas turbine generator

### ISSUE THREAD

**Issue by Mementh** [bdew-minecraft/generators#77]
whoops thought the link on the page was for the generators 
https://github.com/bdew/bdlib/issues/23

basicaly copy of it.. is that i would love to see more usage states.. right now unless the generator is under a constant full load it wont tell you how much its really using per tick.

@bdew mentioned a few time options and eventually a computer output option.

putting this here as a request :)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
