### ISSUE TITLE
Fluxed redstone cables do not ouput energy from generators?????, they do work with every other mod

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/generators#78]
Fluxed redstone cables are not detected by the generator

http://minecraft.curseforge.com/projects/fluxed-redstone?gameCategorySlug=mc-mods&amp;projectID=240484

**Comment by bdew** [comment]
It looks like those cables can only pull energy, and not have it pushed to them which is how my generators work. You will need some kind of buffer or capacitor between them.

**Comment by winsrp** [comment]
couldn't you make it so that the generators accept energy being pulled? I also raised an issue to them about it, but in order for everything to be compatible with everything why not let it work both ways?

**Comment by bdew** [comment]
It's... problematic. At any rate, it's even worse - their cables use the "basic" MCMP tileentity, which doesn't implement any of the RF interfaces - so the output module can't detect that it supports RF at all. This is something that would need to be fixed on their side.
