### ISSUE TITLE
Request - Make RF cables

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/generators#80]
could you make some RF cables that work all around? Same as your pipes from the other mod? maybe in tiers instead of a suck it all cable? I use fluxed redstone cables, since its the only mod that comes with cables that "work" for 1.8.9

**Comment by bdew** [comment]
Way too busy with other stuff at the moment.

[Buildcraft ](https://github.com/AlexIIL/BC-Temp-releases/releases) has working energy pipes for now.

**Comment by winsrp** [comment]
Buildcraft does not works for 1.8.9, the only mod cables in 1.8.9 is fluxed redstone which does not works with your mod.

**Comment by misterfixit** [comment]
Buildcraft does have energy pipes that transfer rf they are called kinesis pipes and yes they are there in 1.8.9

**Comment by bdew** [comment]
Click the link in my previous comment, it's for the 1.8.9 version of BC that works just fine.

**Comment by winsrp** [comment]
I'll be damn... I'm trying those out. Thanks for the info.

**Comment by winsrp** [comment]
So I've seen all the tutorials about BC done all the trials, and I've made 6 examples.

For reference
BC = Buildcraft, FR = fluxed Redstone, PA = progresive automation, AG = Advanced Generators

BC Engine + BC pipes = no power
BC Engine + FR pipes = no power
PA Engine + BC pipes = no power
PA Engine + FR pipes = power yay!
AG Engine + BC pipes = no power
AG Engine + FR pipes = no power

So question here... have you guys tried the BC pipes to see if they actually work on 1.8.9, it cannot be that I'm that stupid.

**Comment by winsrp** [comment]
never mind I just figured out what it was... you need the import pipe attached to the generator then power flows with BC cables... why it has to be so complicated... uhgg

**Comment by misterfixit** [comment]
Yes you need to have a wooden kinesis pipe or an emerald one to input the power into the energy line
