### ISSUE TITLE
RF output for 1.8.9

### ISSUE THREAD

**Issue by Congrave** [bdew-minecraft/generators#81]
I'm trying to use this mod in a personal dedicated server. I've been testing it out but for the life of me couldn't figure out how power is suppose to come out of the turbine generators. I don't see a recipe for power emitters. I looked at the cfg files and I saw that it naturally gives you either an RF or a EU output if you have certain mods installed. I have neither but I have RF operated machines and such. Neotech, StorageNetwork, etc.

Using
- generators 0.9.19.5
- bdlib 1.10.0.26

**Comment by nlxdodge** [comment]
I have this issue to the generators create RF but no energy pipe can extract it.
Also tested with:
- generators 0.9.19.5-mc1.8.9
- bdlib-1.10.0.25-mc1.8.9
- NeoTech-1.8.9-2.4.1
- Fluxed Redstone-1.3.0.31

I suppose that you didn't have the time yet to implement the normal RF Api from the cofhteam?

**Comment by bdew** [comment]
It does use the official RF API. 

From my tests:
- It works with BuildCraft - you need a wooden or emerald kinesis pipe, unlike 1.7.10 versions
- It doesn't work with Fluxed Redstone - their pipe don't implement any of the RF interfaces on the pipe TE, so can't be detected.
- It doesn't work with NeoTech pipes, didn't investigate yet why exactly. If you stick a machine from NeoTech directly next to a generator it works, so i'm guessing their pipes are doing something weird as well.

**Comment by Congrave** [comment]
I see to. Yeah their pipes are weird and I might try buildcraft again. It's been a few years but I haven't found a decent set of pipes since I started 1.8.9. I'll try fluxed redstone since I didn't know you can use any side to as an output. It's not stated in the wiki; I don't think, so it was a bit confusing.

**Comment by Congrave** [comment]
I didn't know about the fluxed redstone. This is what I get for speed reading. I'll try to see if I can't find a portable cell in one of my mods to cover for that flaw for Neotech's pipes. Thanks again.
