### ISSUE TITLE
[Feature Request] Add power cables!!

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/generators#84]
ok with all the issues you have been currently fixing is nice that your mod is stating to become compatible with well, almost any other mod, but it will really be great if you provide your own cables so that we don't have to install other mods just for cables. 

Here is the plan
First the cool one, High voltage cable, that works like the pressure pipes, but with RF. (Expensive cable) Emerald cable / ender cable
1 tier down ( 8192 RF/t) diamond cable
1 tier down (1024 RF/t) gold cable
1 tier down (128 RF/t) iron cable

Ur the man! =D

**Comment by bdew** [comment]
Sorry but no, at least not at the moment. Pipe systems tend to be a pain to get right and a lot other things need doing more urgently and there's a bunch of pipe mods for 1.8 and more are coming up.

PS - EnderIO now has 1.8.9 builds on their [jenkins](http://ci.tterrag.com/) and it's one of the best pipes around and everything works with all my mods afaik :P
