### ISSUE TITLE
Crash at startup with Forge 1809

### ISSUE THREAD

**Issue by kwpugh** [bdew-minecraft/generators#86]
report:  http://pastebin.com/raw/jfhhn0QZ

**Comment by bdew** [comment]
Forge change broke some stuff. Update incoming.

MinecraftForge/MinecraftForge@756c58d5cb01ed33e9bbc165ab62cc62244d6bb1

**Comment by bdew** [comment]
Fixed in 09b481f992ec9eec65cbf0c6ff94c904a5f8ddda

Don't forget to update BDLib

**Comment by kwpugh** [comment]
Tested, works fine on server.  Thank you.
