### ISSUE TITLE
Item Input Port not working with NeoTech item pipe

### ISSUE THREAD

**Issue by JCMais** [bdew-minecraft/generators#90]
Minecraft version: 1.9.2
Forge Version: 1863
Advanced Generators: 9.20.7
NeoTech version: 1.9-3.0.5

![2016-04-21_17 46 46](https://cloud.githubusercontent.com/assets/1041647/14723773/1eaf46cc-07e9-11e6-8de2-049278470915.png)

From what I can see, this happens because the item is not implementing the forge interface IItemHandler.

**Comment by bdew** [comment]
Known issue. I'm in the process of updating everything to IItemHandler, but it requires some backend changes to how stuff is stored and how different modules in multiblocks interact. Will be fixed soon(tm).

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
