### ISSUE TITLE
(1.8.9) Not registering other mod materials

### ISSUE THREAD

**Issue by magerooster** [bdew-minecraft/generators#92]
https://paste.ee/p/ZfiiK ("Error while processing RsRecipeShaped...")
It's throwing an error while reading the configs.

I know at the very least part of the problem is that EnderIO has changed the material name for vibrant alloy to enderio:ingotVibrantAlloy from enderio:ingotPhasedGold. Likewise, IC2 has changed the material name of advanced alloy to ic2:crafting. The other IC2 item names have changed as well: ic2:advanced_re_battery, ic2:energy_crystal, ic2:lapotron_crystal and I'm not sure what I:IC2:itemRecipePart@12 was.

**Comment by bdew** [comment]
Yeah, the current builds for 1.8.9 were made before the other mods had versions out for 1.8.9.

I'm planning to do a last round of updates for 1.8.9 before i fully move to 1.9, i'll fix it when i get to it.

**Comment by BBoldt** [comment]
Thanks for not abandoning 1.8.9 entirely. There is still sort of a unique blend of mods still on 1.8 that aren't 1.9 yet.

**Comment by bdew** [comment]
Should be fixed now
