### ISSUE TITLE
Add support to PowerAdvantage Oil in the Gas Turbine

### ISSUE THREAD

**Issue by JCMais** [bdew-minecraft/generators#93]
There are two kinds of oil, crude oil and refined oil.

http://drcyano.wikidot.com/crude-oil
http://drcyano.wikidot.com/refined-oil

Here is how they are defined in the mod:

https://github.com/cyanobacterium/PowerAdvantageAPI/blob/master/src/main/java/cyano/poweradvantage/init/Fluids.java#L54

https://github.com/cyanobacterium/PowerAdvantageAPI/blob/master/src/main/java/cyano/poweradvantage/init/Fuels.java#L23

If it's possible to add it using a config option, let me know.

**Comment by bdew** [comment]
Added refined fuel to the default configs. 

From my testing it produces ~240k RF from a bucket in the mod itself (using a steam boiler -> steam-rf transformer), so i balanced it's value around that. I'm not really familiar with power advantage so if this is wrong - please tell me :P
