### ISSUE TITLE
IC2 Classic recipes for Advanced Alloy Turbines

### ISSUE THREAD

**Issue by Fortanono** [bdew-minecraft/generators#94]
If you have IC2 Classic as opposed to Experimental, the Adv. Alloy turbines will register, but their recipes don't work. My guess is that they have different IDs or something. This should probably be changed, as both your mod and IC2 Classic are in FTB's upcoming pack, Inventions.

Please note that Classic does not have a Refined Iron Shaft, so the recipes won't be perfect, but just having another piece of Advanced Alloy in the middle of it should work.

**Comment by bdew** [comment]
This is annoying, since they both use the same mod id i have no good way of identifying which one is installed...

**Comment by bdew** [comment]
Ok, i'll added a workaround, with detection based on version number. If IC2exp ever reaches version 2.2.999 - this will be a problem... but hopefully that doesn't happen in 1.7.10, and i'll figure out a better solution for 1.9 :P
