### ISSUE TITLE
[1.8.9] missing recipe for Advanced Pressure Valve

### ISSUE THREAD

**Issue by lehjr** [bdew-minecraft/generators#96]
The Advanced Pressure Valve is required to craft the Gas Mix Compressor, but doesn't appear to have a recipe of it's own. Might also be missing in 1.9.x too.

**Comment by bdew** [comment]
Nope. https://github.com/search?p=1&q=%22Can%27t+load+with+Dragonapi%22&ref=searchresults&type=Issues&utf8=%E2%9C%93

**Comment by lehjr** [comment]
I have no idea what your link is referencing

**Comment by bdew** [comment]
Errr, sorry... that was meant for a different bug report. I'll check the recipe, it should be there...

**Comment by bdew** [comment]
Do you have enderio installed as well?

**Comment by lehjr** [comment]
yes, it's the last 1.8.9 build before they switched to 1.9.4 builds
EnderIO-1.8.9-3.0.0.26_alpha.jar

**Comment by bdew** [comment]
Ok there seems to be a bug with the EnderIO and IC2 versions of this recipe, and if either of those are present the vanilla recipe is disabled - so it becomes uncraftable.

Will push a fix in a minute.

**Comment by lehjr** [comment]
Great, thanks :D

**Comment by bdew** [comment]
Should be fixed in this build: http://minecraft.curseforge.com/projects/advanced-generators/files/2304228
