### ISSUE TITLE
[1.9.4] Advanced generators not recognizing Ethanol from Forestry

### ISSUE THREAD

**Issue by Kazzamkablam** [bdew-minecraft/generators#97]
It seems now that Forestry updated to 1.9.4, ethanol is not recognized by advanced generators as fuel.

Based on wiki it should: Biofuel / Bioethanol (Forestry, MFR, other mods) – 800 RF/mB
version: Advanced Generators 0.9.20.1

**Comment by ChaoticTabris** [comment]
Somehow the "All The Mods" pack on curse supposely fixed that. Maybe it can be done by editing the config?

**Comment by RyanP1991** [comment]
Just looked at their config:

---

recipes {
    turbine-fuel: "bio.ethanol" 80 MJ/mB

## }

**Comment by bdew** [comment]
Fixed in latest build.
