### ISSUE TITLE
[0.9.20.1] Generators/tanks visually break when returning from the nether

### ISSUE THREAD

**Issue by OhiraKyou** [bdew-minecraft/generators#98]
Minecraft 1.9.4
Forge 1.9.4-12.17.0.1932
Advanced Generators 0.9.20.1

[Screenshot](http://i.imgur.com/mTiUU87.png)

After returning from the nether, all advanced generators and pressure pipes tanks are visually broken. They still work, but indicators and WAILA information suggests that they aren't valid. Replacing a piece fixes that one connection, and hovering over the fixed blocks shows WAILA information for the multiblock. But, the controller has to be replaced to fix the entire multiblock at once; reloading the world doesn't help.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
